CREATE TABLE "author_filing" (
	"display_key" text PRIMARY KEY NOT NULL,
	"filing_name" text NOT NULL,
	"is_corporate" integer DEFAULT 0 NOT NULL,
	"note" text DEFAULT ''
);
--> statement-breakpoint
CREATE TABLE "book_authors" (
	"book_id" integer NOT NULL,
	"position" integer NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "book_authors_pkey" PRIMARY KEY("book_id","position")
);
--> statement-breakpoint
CREATE TABLE "books" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "books_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"isbn13" text DEFAULT '',
	"isbn10" text DEFAULT '',
	"title" text NOT NULL,
	"subtitle" text DEFAULT '',
	"authors" text DEFAULT '',
	"publisher" text DEFAULT '',
	"published" text DEFAULT '',
	"pages" text DEFAULT '',
	"notes" text DEFAULT '',
	"shelf_range" text NOT NULL,
	"is_fiction" integer NOT NULL,
	"classification_source" text DEFAULT 'auto',
	"classification_confidence" text DEFAULT 'unknown',
	"author_filing" text COLLATE "C" DEFAULT '',
	"series_name" text DEFAULT '',
	"series_index" double precision,
	"title_filing" text COLLATE "C" DEFAULT '',
	"sort_key" text COLLATE "C" NOT NULL,
	"location" text DEFAULT '',
	"lookup_source" text DEFAULT '',
	"front_image" text DEFAULT '',
	"back_image" text DEFAULT '',
	"edge_image" text DEFAULT '',
	"cover_image" text DEFAULT '',
	"cover_checked_at" text,
	"front_hash" text DEFAULT '',
	"cover_hash" text DEFAULT '',
	"front_crop" text DEFAULT '',
	"back_crop" text DEFAULT '',
	"edge_crop" text DEFAULT '',
	"cropped" text DEFAULT '',
	"isbn_source" text DEFAULT '',
	"ocr_text" text DEFAULT '',
	"scanned_at" text NOT NULL,
	"shelved_at" text,
	"checked_out_at" text
);
--> statement-breakpoint
CREATE TABLE "captures" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "captures_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"status" text DEFAULT 'pending' NOT NULL,
	"front_image" text DEFAULT '',
	"back_image" text DEFAULT '',
	"edge_image" text DEFAULT '',
	"isbn13" text DEFAULT '',
	"isbn10" text DEFAULT '',
	"isbn_source" text DEFAULT '',
	"title_guess" text DEFAULT '',
	"cover_text" text DEFAULT '',
	"analysed" text DEFAULT '',
	"draft_json" text DEFAULT '',
	"edit_json" text DEFAULT '',
	"edited_by" text DEFAULT '',
	"edited_at" text,
	"note" text DEFAULT '',
	"claimed_by" text DEFAULT '',
	"claimed_at" text,
	"front_crop" text DEFAULT '',
	"back_crop" text DEFAULT '',
	"edge_crop" text DEFAULT '',
	"cropped" text DEFAULT '',
	"front_hash" text DEFAULT '',
	"book_id" integer,
	"created_at" text NOT NULL,
	"processed_at" text
);
--> statement-breakpoint
CREATE TABLE "separators" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "separators_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shelf_range" text NOT NULL,
	"kind" text DEFAULT 'shelf' NOT NULL,
	"starts_at" text COLLATE "C" NOT NULL,
	"position" integer NOT NULL,
	"note" text DEFAULT '',
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shelf_ranges" (
	"shelf_range" text PRIMARY KEY NOT NULL,
	"start_label" text NOT NULL,
	"start_shelf" integer DEFAULT 1 NOT NULL,
	"start_area" integer DEFAULT 0 NOT NULL,
	"note" text DEFAULT ''
);
--> statement-breakpoint
ALTER TABLE "book_authors" ADD CONSTRAINT "book_authors_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "captures" ADD CONSTRAINT "captures_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_books_shelf" ON "books" USING btree ("shelf_range","sort_key");--> statement-breakpoint
CREATE INDEX "idx_books_isbn13" ON "books" USING btree ("isbn13");--> statement-breakpoint
CREATE INDEX "idx_captures_status" ON "captures" USING btree ("status","id");--> statement-breakpoint
CREATE INDEX "idx_separators" ON "separators" USING btree ("shelf_range","position");