CREATE TABLE "book_tag" (
	"book_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	"source" text NOT NULL,
	"confidence" text DEFAULT 'unknown' NOT NULL,
	"added_at" text NOT NULL,
	CONSTRAINT "book_tag_pkey" PRIMARY KEY("book_id","tag_id","source")
);
--> statement-breakpoint
CREATE TABLE "tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text COLLATE "C" NOT NULL,
	"label" text NOT NULL,
	"note" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "book_tag" ADD CONSTRAINT "book_tag_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "book_tag" ADD CONSTRAINT "book_tag_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_book_tag_tag" ON "book_tag" USING btree ("tag_id");--> statement-breakpoint
CREATE UNIQUE INDEX "tag_slug_key" ON "tag" USING btree ("slug");