CREATE TABLE "author" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "author_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"is_corporate" integer DEFAULT 0 NOT NULL,
	"note" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "author_alias" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "author_alias_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"author_id" integer NOT NULL,
	"display_name" text NOT NULL,
	"filing_name" text COLLATE "C" NOT NULL,
	"is_primary" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "book_author" (
	"book_id" integer NOT NULL,
	"position" integer NOT NULL,
	"author_alias_id" integer NOT NULL,
	CONSTRAINT "book_author_pkey" PRIMARY KEY("book_id","position")
);
--> statement-breakpoint
ALTER TABLE "author_alias" ADD CONSTRAINT "author_alias_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "public"."author"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "book_author" ADD CONSTRAINT "book_author_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "book_author" ADD CONSTRAINT "book_author_author_alias_id_fkey" FOREIGN KEY ("author_alias_id") REFERENCES "public"."author_alias"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "author_alias_display_name_key" ON "author_alias" USING btree ("display_name");--> statement-breakpoint
CREATE INDEX "idx_author_alias_author" ON "author_alias" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX "idx_book_author_alias" ON "book_author" USING btree ("author_alias_id");