CREATE TABLE "capture" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "capture_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"book_id" integer NOT NULL,
	"kind" text NOT NULL,
	"file" text NOT NULL,
	"crop_file" text DEFAULT '' NOT NULL,
	"examined" boolean DEFAULT false NOT NULL,
	"hash" text DEFAULT '' NOT NULL,
	"taken_at" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "capture" ADD CONSTRAINT "capture_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "capture_book_file_key" ON "capture" USING btree ("book_id","file");--> statement-breakpoint
CREATE INDEX "idx_capture_book" ON "capture" USING btree ("book_id","taken_at");