DROP VIEW "public"."shelved_books";--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "title_guess" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "cover_text" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "analysed" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "draft_json" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "edit_json" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "edited_by" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "edited_at" text;--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "scan_note" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "claimed_by" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "claimed_at" text;--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "processed_at" text;--> statement-breakpoint
CREATE INDEX "idx_books_queued" ON "books" USING btree ("state","id") WHERE "state" IN ('scanned', 'unidentified', 'identified');--> statement-breakpoint
CREATE VIEW "public"."catalogued_books" AS (select "id", "isbn13", "isbn10", "title", "subtitle", "authors", "publisher", "published", "pages", "notes", "shelf_range", "is_fiction", "classification_source", "classification_confidence", "author_filing", "series_name", "series_index", "title_filing", "sort_key", "location", "lookup_source", "front_image", "back_image", "edge_image", "cover_image", "cover_checked_at", "front_hash", "cover_hash", "front_crop", "back_crop", "edge_crop", "cropped", "isbn_source", "ocr_text", "scanned_at", "shelved_at", "checked_out_at", "state", "title_guess", "cover_text", "analysed", "draft_json", "edit_json", "edited_by", "edited_at", "scan_note", "claimed_by", "claimed_at", "processed_at" from "books" where "books"."state" in ('shelved', 'checked_out', 'withdrawn'));--> statement-breakpoint
CREATE VIEW "public"."queued_books" AS (select "id", "isbn13", "isbn10", "title", "subtitle", "authors", "publisher", "published", "pages", "notes", "shelf_range", "is_fiction", "classification_source", "classification_confidence", "author_filing", "series_name", "series_index", "title_filing", "sort_key", "location", "lookup_source", "front_image", "back_image", "edge_image", "cover_image", "cover_checked_at", "front_hash", "cover_hash", "front_crop", "back_crop", "edge_crop", "cropped", "isbn_source", "ocr_text", "scanned_at", "shelved_at", "checked_out_at", "state", "title_guess", "cover_text", "analysed", "draft_json", "edit_json", "edited_by", "edited_at", "scan_note", "claimed_by", "claimed_at", "processed_at" from "books" where "books"."state" in ('scanned', 'unidentified', 'identified'));--> statement-breakpoint
CREATE VIEW "public"."shelved_books" AS (select "id", "isbn13", "isbn10", "title", "subtitle", "authors", "publisher", "published", "pages", "notes", "shelf_range", "is_fiction", "classification_source", "classification_confidence", "author_filing", "series_name", "series_index", "title_filing", "sort_key", "location", "lookup_source", "front_image", "back_image", "edge_image", "cover_image", "cover_checked_at", "front_hash", "cover_hash", "front_crop", "back_crop", "edge_crop", "cropped", "isbn_source", "ocr_text", "scanned_at", "shelved_at", "checked_out_at", "state", "title_guess", "cover_text", "analysed", "draft_json", "edit_json", "edited_by", "edited_at", "scan_note", "claimed_by", "claimed_at", "processed_at" from "books" where "books"."state" = 'shelved');