CREATE TABLE "area" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "area_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fixture_id" integer NOT NULL,
	"position" integer NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"starts_at" text COLLATE "C" DEFAULT '' NOT NULL,
	"sort_strategy" text DEFAULT 'inherit' NOT NULL,
	"note" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "collection" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "collection_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text DEFAULT '' NOT NULL,
	"default_sort_strategy" text DEFAULT 'author' NOT NULL,
	"note" text DEFAULT '' NOT NULL,
	CONSTRAINT "collection_default_sort_strategy_check" CHECK ("default_sort_strategy" <> 'inherit')
);
--> statement-breakpoint
CREATE TABLE "fixture" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fixture_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"collection_id" integer NOT NULL,
	"kind" text DEFAULT 'bookshelf' NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"position" integer NOT NULL,
	"sort_strategy" text DEFAULT 'inherit' NOT NULL,
	"note" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "placement_rule" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "placement_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"area_id" integer,
	"fixture_id" integer,
	"priority" integer DEFAULT 0 NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	CONSTRAINT "placement_rule_target_check" CHECK (num_nonnulls("area_id", "fixture_id") = 1)
);
--> statement-breakpoint
CREATE TABLE "rule_condition" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rule_condition_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rule_id" integer NOT NULL,
	"field" text NOT NULL,
	"operator" text NOT NULL,
	"value" text NOT NULL,
	CONSTRAINT "rule_condition_field_check" CHECK ("field" IN ('tag')),
	CONSTRAINT "rule_condition_operator_check" CHECK ("operator" IN ('is', 'under'))
);
--> statement-breakpoint
CREATE TABLE "sort_strategy" (
	"code" text PRIMARY KEY NOT NULL,
	"label" text NOT NULL,
	"is_inherit" boolean DEFAULT false NOT NULL,
	"available" boolean DEFAULT true NOT NULL,
	"note" text DEFAULT '' NOT NULL,
	CONSTRAINT "sort_strategy_code_check" CHECK ("code" IN ('inherit', 'author', 'title', 'published', 'tag'))
);
--> statement-breakpoint
ALTER TABLE "area" ADD CONSTRAINT "area_fixture_id_fkey" FOREIGN KEY ("fixture_id") REFERENCES "public"."fixture"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "area" ADD CONSTRAINT "area_sort_strategy_fkey" FOREIGN KEY ("sort_strategy") REFERENCES "public"."sort_strategy"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "collection" ADD CONSTRAINT "collection_default_sort_strategy_fkey" FOREIGN KEY ("default_sort_strategy") REFERENCES "public"."sort_strategy"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fixture" ADD CONSTRAINT "fixture_collection_id_fkey" FOREIGN KEY ("collection_id") REFERENCES "public"."collection"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fixture" ADD CONSTRAINT "fixture_sort_strategy_fkey" FOREIGN KEY ("sort_strategy") REFERENCES "public"."sort_strategy"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "placement_rule" ADD CONSTRAINT "placement_rule_area_id_fkey" FOREIGN KEY ("area_id") REFERENCES "public"."area"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "placement_rule" ADD CONSTRAINT "placement_rule_fixture_id_fkey" FOREIGN KEY ("fixture_id") REFERENCES "public"."fixture"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rule_condition" ADD CONSTRAINT "rule_condition_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "public"."placement_rule"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "area_fixture_position_key" ON "area" USING btree ("fixture_id","position");--> statement-breakpoint
CREATE INDEX "idx_area_anchor" ON "area" USING btree ("fixture_id","starts_at");--> statement-breakpoint
CREATE INDEX "idx_fixture_collection" ON "fixture" USING btree ("collection_id","position");--> statement-breakpoint
CREATE INDEX "idx_placement_rule_order" ON "placement_rule" USING btree ("priority","id");--> statement-breakpoint
CREATE INDEX "idx_rule_condition_rule" ON "rule_condition" USING btree ("rule_id");