CREATE TABLE "book_placement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "book_placement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"book_id" integer NOT NULL,
	"kind" text NOT NULL,
	"area_id" integer,
	"sort_key" text COLLATE "C" DEFAULT '' NOT NULL,
	"rule_id" integer,
	"actor" text NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"created_at" text NOT NULL,
	CONSTRAINT "book_placement_kind_check" CHECK ("kind" IN ('assigned', 'placed', 'pinned', 'checked_out', 'checked_in', 'withdrawn')),
	CONSTRAINT "book_placement_actor_check" CHECK ("actor" IN ('person', 'rules', 'migration')),
	CONSTRAINT "book_placement_area_check" CHECK (("kind" IN ('assigned', 'placed', 'pinned')) = ("area_id" IS NOT NULL)),
	CONSTRAINT "book_placement_rule_check" CHECK ("rule_id" IS NULL OR "kind" = 'assigned')
);
--> statement-breakpoint
DROP VIEW "public"."catalogued_books";--> statement-breakpoint
DROP VIEW "public"."queued_books";--> statement-breakpoint
DROP VIEW "public"."shelved_books";--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "current_area_id" integer;--> statement-breakpoint
ALTER TABLE "book_placement" ADD CONSTRAINT "book_placement_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "book_placement" ADD CONSTRAINT "book_placement_area_id_fkey" FOREIGN KEY ("area_id") REFERENCES "public"."area"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "book_placement" ADD CONSTRAINT "book_placement_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "public"."placement_rule"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_book_placement_book" ON "book_placement" USING btree ("book_id","id");--> statement-breakpoint
ALTER TABLE "books" ADD CONSTRAINT "books_current_area_id_fkey" FOREIGN KEY ("current_area_id") REFERENCES "public"."area"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_books_current_area" ON "books" USING btree ("current_area_id","sort_key");--> statement-breakpoint
CREATE VIEW "public"."catalogued_books" AS (select "id", "isbn13", "isbn10", "title", "subtitle", "authors", "publisher", "published", "pages", "notes", "shelf_range", "is_fiction", "classification_source", "classification_confidence", "author_filing", "series_name", "series_index", "title_filing", "sort_key", "location", "lookup_source", "front_image", "back_image", "edge_image", "cover_image", "cover_checked_at", "front_hash", "cover_hash", "front_crop", "back_crop", "edge_crop", "cropped", "isbn_source", "ocr_text", "scanned_at", "shelved_at", "checked_out_at", "state", "title_guess", "cover_text", "analysed", "draft_json", "edit_json", "edited_by", "edited_at", "scan_note", "claimed_by", "claimed_at", "processed_at", "current_area_id" from "books" where "books"."state" in ('shelved', 'checked_out', 'withdrawn'));--> statement-breakpoint
CREATE VIEW "public"."queued_books" AS (select "id", "isbn13", "isbn10", "title", "subtitle", "authors", "publisher", "published", "pages", "notes", "shelf_range", "is_fiction", "classification_source", "classification_confidence", "author_filing", "series_name", "series_index", "title_filing", "sort_key", "location", "lookup_source", "front_image", "back_image", "edge_image", "cover_image", "cover_checked_at", "front_hash", "cover_hash", "front_crop", "back_crop", "edge_crop", "cropped", "isbn_source", "ocr_text", "scanned_at", "shelved_at", "checked_out_at", "state", "title_guess", "cover_text", "analysed", "draft_json", "edit_json", "edited_by", "edited_at", "scan_note", "claimed_by", "claimed_at", "processed_at", "current_area_id" from "books" where "books"."state" in ('scanned', 'unidentified', 'identified'));--> statement-breakpoint
CREATE VIEW "public"."shelved_books" AS (select "id", "isbn13", "isbn10", "title", "subtitle", "authors", "publisher", "published", "pages", "notes", "shelf_range", "is_fiction", "classification_source", "classification_confidence", "author_filing", "series_name", "series_index", "title_filing", "sort_key", "location", "lookup_source", "front_image", "back_image", "edge_image", "cover_image", "cover_checked_at", "front_hash", "cover_hash", "front_crop", "back_crop", "edge_crop", "cropped", "isbn_source", "ocr_text", "scanned_at", "shelved_at", "checked_out_at", "state", "title_guess", "cover_text", "analysed", "draft_json", "edit_json", "edited_by", "edited_at", "scan_note", "claimed_by", "claimed_at", "processed_at", "current_area_id" from "books" where "books"."state" = 'shelved');