/**
 * Postgres schema and driver. The second implementation of `Db`, and a new
 * file rather than an edit to driver.ts, which is what the seam was for.
 *
 * **This is the default as of stage G.** `BOOKSCAN_DB=sqlite` is what reaches
 * db.ts instead, and it stays a supported configuration until stage I: the
 * owner's catalogue is still a SQLite file until stage H moves it.
 *
 * The schema below is a deliberately literal translation of the one in db.ts.
 * That file stays the authority on what each column is for and why it exists;
 * repeating two hundred lines of that prose here would only give it somewhere
 * to drift. What is written here is the part that is about Postgres: every
 * place the type had to be chosen rather than copied, and why the obvious
 * choice was refused.
 *
 * Two of db.ts's functions are deliberately absent. `addMissingColumns` and
 * `migrateSeparators` bring an old SQLite file forward, and there is exactly
 * one such file in the world; it gets brought forward by the SQLite code path
 * once, immediately before the data migration reads it (stage H).
 * `SCHEMA_VERSION` goes with them: it was stored in a SQLite pragma.
 *
 * Postgres does have a migration chain as of #172, and it is Drizzle's, in
 * `web/infrastructure/db/migrations`. `applySchema` at the bottom of this file
 * runs it. Nothing in this file decides what the schema is any more; the
 * constant below is what the first migration is checked against.
 */

import { AsyncLocalStorage } from 'node:async_hooks'
import pg from 'pg'
import { migrateToLatest } from '../infrastructure/db/migrate'
import { bindParams, lockKey, numbered, type Db, type Params, type TxOptions } from './driver'

const { Pool } = pg
type PoolClient = pg.PoolClient

/**
 * Every column keeps the type that produces the same JavaScript value it
 * produces today, because the API contract and the React client depend on it.
 * The four decisions worth arguing about are marked at the column.
 *
 * **Nothing runs this any more.** Since #172 the schema is created by the
 * baseline migration under `web/infrastructure/db/migrations`, generated from
 * the Drizzle schema. This is kept, and kept exactly as it was, because it is
 * what that baseline is proved against: `infrastructure/db/migrate.test.ts`
 * builds one database from this constant and one from the migration and diffs
 * them, column for column, index for index and constraint for constraint. A
 * baseline that claims to reproduce today's schema and is only ever compared
 * against itself claims nothing.
 *
 * So do not edit it to describe a change. A schema change goes in the Drizzle
 * schema and gets a migration; this constant is the fixed point that says the
 * conversion was faithful, and it stops being useful the moment it moves.
 */
export const SCHEMA = `
CREATE TABLE IF NOT EXISTS books (
    -- BY DEFAULT rather than ALWAYS, so the stage H migration can insert the
    -- ids the SQLite rows already have. book_authors.book_id, captures.book_id
    -- and every cover filename on disk depend on those ids surviving.
    id                        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn13                    text    DEFAULT '',
    isbn10                    text    DEFAULT '',
    title                     text    NOT NULL,
    subtitle                  text    DEFAULT '',
    authors                   text    DEFAULT '',
    publisher                 text    DEFAULT '',
    published                 text    DEFAULT '',
    pages                     text    DEFAULT '',
    notes                     text    DEFAULT '',

    shelf_range               text    NOT NULL,
    -- integer, not boolean. BookRow.is_fiction is a number, the JSON contract
    -- carries 0 and 1, and the client reads them.
    is_fiction                integer NOT NULL,
    classification_source     text    DEFAULT 'auto',
    classification_confidence text    DEFAULT 'unknown',

    -- COLLATE "C" is load-bearing on these four columns and on
    -- separators.starts_at. See the note under SORT_KEY_COLUMNS below.
    author_filing             text COLLATE "C" DEFAULT '',
    series_name               text    DEFAULT '',
    series_index              double precision,
    title_filing              text COLLATE "C" DEFAULT '',
    sort_key                  text COLLATE "C" NOT NULL,

    location                  text    DEFAULT '',
    lookup_source             text    DEFAULT '',

    front_image               text    DEFAULT '',
    back_image                text    DEFAULT '',
    edge_image                text    DEFAULT '',
    cover_image               text    DEFAULT '',
    -- text, not timestamptz, and the same goes for every _at column below.
    -- node-postgres hands a timestamptz back as a Date, which would change
    -- every JSON payload the client and the end to end suite read. ISO-8601
    -- text sorts correctly anyway, which is the only thing anything does to it.
    cover_checked_at          text,
    front_hash                text    DEFAULT '',
    cover_hash                text    DEFAULT '',
    front_crop                text    DEFAULT '',
    back_crop                 text    DEFAULT '',
    edge_crop                 text    DEFAULT '',
    cropped                   text    DEFAULT '',
    isbn_source               text    DEFAULT '',
    -- Vestigial; always ''. See the comment on this column in db.ts.
    ocr_text                  text    DEFAULT '',

    scanned_at                text    NOT NULL,
    shelved_at                text,
    checked_out_at            text
);

-- Inherits sort_key's COLLATE "C", so the index and the comparisons that use
-- it cannot disagree. An index built under a different collation from the
-- query is the failure mode that reorders a shelf without erroring.
CREATE INDEX IF NOT EXISTS idx_books_shelf  ON books (shelf_range, sort_key);
CREATE INDEX IF NOT EXISTS idx_books_isbn13 ON books (isbn13);

CREATE TABLE IF NOT EXISTS book_authors (
    book_id  integer NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    position integer NOT NULL,
    name     text    NOT NULL,
    PRIMARY KEY (book_id, position)
);

CREATE TABLE IF NOT EXISTS author_filing (
    display_key  text PRIMARY KEY,
    filing_name  text NOT NULL,
    is_corporate integer NOT NULL DEFAULT 0,
    note         text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS shelf_ranges (
    shelf_range text    PRIMARY KEY,
    start_label text    NOT NULL,
    start_shelf integer NOT NULL DEFAULT 1,
    start_area  integer NOT NULL DEFAULT 0,
    note        text    DEFAULT ''
);

CREATE TABLE IF NOT EXISTS captures (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       text    NOT NULL DEFAULT 'pending',
    front_image  text    DEFAULT '',
    back_image   text    DEFAULT '',
    edge_image   text    DEFAULT '',
    isbn13       text    DEFAULT '',
    isbn10       text    DEFAULT '',
    isbn_source  text    DEFAULT '',
    title_guess  text    DEFAULT '',
    cover_text   text    DEFAULT '',
    analysed     text    DEFAULT '',
    draft_json   text    DEFAULT '',
    edit_json    text    DEFAULT '',
    edited_by    text    DEFAULT '',
    edited_at    text,
    note         text    DEFAULT '',
    claimed_by   text    DEFAULT '',
    claimed_at   text,
    front_crop   text    DEFAULT '',
    back_crop    text    DEFAULT '',
    edge_crop    text    DEFAULT '',
    cropped      text    DEFAULT '',
    front_hash   text    DEFAULT '',
    book_id      integer REFERENCES books(id) ON DELETE SET NULL,
    created_at   text    NOT NULL,
    processed_at text
);

CREATE INDEX IF NOT EXISTS idx_captures_status ON captures (status, id);

CREATE TABLE IF NOT EXISTS separators (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelf_range text    NOT NULL,
    kind        text    NOT NULL DEFAULT 'shelf',
    -- Compared against books.sort_key to find shelf boundaries, so it has to
    -- order the same way sort_key does or a boundary lands between the wrong
    -- two books.
    starts_at   text COLLATE "C" NOT NULL,
    position    integer NOT NULL,
    note        text    DEFAULT '',
    created_at  text    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_separators ON separators (shelf_range, position);
`

/**
 * The columns that must not be compared by a linguistic collation, and the
 * tables they live in.
 *
 * `sort_key` is the spine of the product. `Store.neighbours` seeks either side
 * of one with `<` and `>`, `Shelves.booksIn` orders by it, and
 * `separators.starts_at` is compared against it to find where a shelf begins.
 * SQLite compares text byte by byte with no exceptions; Postgres compares using
 * the collation of the column, and a glibc `en_US.utf8` one ignores punctuation
 * on the first pass, folds case, and files accented characters beside their
 * unaccented forms. Two keys SQLite orders one way come back the other way.
 *
 * That does not throw and does not fail a smoke test. It reorders a shelf, or
 * moves one book past a separator, and the app then tells somebody to put a
 * book in the wrong place.
 *
 * `sort_key` also contains `\x1f`, the unit separator that joins its
 * components, and the `.` in a padded series index, both of which are exactly
 * the sort of character a linguistic collation is entitled to treat as
 * ignorable.
 *
 * Exported so a test can assert the declaration rather than trusting this
 * comment. See db.pg.test.ts, which reads the collation back out of the
 * catalogue and also shows the fixture coming out in the wrong order without it.
 */
export const SORT_KEY_COLUMNS: readonly (readonly [table: string, column: string])[] = [
  ['books', 'sort_key'],
  ['books', 'author_filing'],
  ['books', 'title_filing'],
  ['separators', 'starts_at'],
]

/**
 * Turn a connection string into something node-postgres understands, in either
 * of the two spellings this app is handed one in.
 *
 * **Aspire does not hand out a URL.** `ConnectionStrings__bookscan` arrives as
 * ADO.NET keywords, `Host=localhost;Port=65156;Username=postgres;Password=...;
 * Database=bookscan`, because the connection string is produced for the .NET
 * clients Aspire was built around. node-postgres reads only the
 * `postgres://user:pass@host:port/db` URL form and would take the whole
 * keyword string as a hostname. The plan said to read the variable the way
 * `PORT` is read, which is true of getting it and not of using it.
 *
 * Both are accepted: a URL passes straight through, so
 * `BOOKSCAN_TEST_DATABASE_URL` and a hand-written connection still work.
 */
export function connectionConfig(value: string): pg.PoolConfig {
  const trimmed = value.trim()
  if (/^postgres(ql)?:\/\//i.test(trimmed)) return { connectionString: trimmed }

  // Walked rather than split on ';', because ADO allows a quoted value and
  // that is how a password containing a separator is spelled. Splitting first
  // truncates such a password at the separator, which surfaces as an
  // authentication failure that says nothing about the string being cut.
  const fields = new Map<string, string>()
  let i = 0
  while (i < trimmed.length) {
    const equals = trimmed.indexOf('=', i)
    if (equals === -1) break
    const key = trimmed.slice(i, equals).trim().toLowerCase().replace(/\s+/g, '')
    i = equals + 1

    let field: string
    const quote = trimmed[i]
    if (quote === "'" || quote === '"') {
      i += 1
      field = ''
      while (i < trimmed.length) {
        if (trimmed[i] === quote) {
          // A doubled quote is an escaped one, as it is in SQL.
          if (trimmed[i + 1] === quote) { field += quote; i += 2; continue }
          i += 1
          break
        }
        field += trimmed[i]
        i += 1
      }
      const next = trimmed.indexOf(';', i)
      i = next === -1 ? trimmed.length : next + 1
    } else {
      const next = trimmed.indexOf(';', i)
      const stop = next === -1 ? trimmed.length : next
      field = trimmed.slice(i, stop).trim()
      i = stop + 1
    }

    if (key) fields.set(key, field)
  }

  const pick = (...names: string[]) => names.map((n) => fields.get(n)).find((v) => v !== undefined)

  const port = pick('port')
  return {
    // The aliases ADO.NET and Npgsql accept for the same four things. Listed
    // rather than assumed, because which one arrives is a property of whatever
    // produced the string and not of this app.
    host: pick('host', 'server', 'datasource'),
    port: port ? Number(port) : undefined,
    user: pick('username', 'userid', 'user'),
    password: pick('password', 'pwd'),
    database: pick('database', 'initialcatalog'),
  }
}

/** Host, port and database. Never the credentials: this reaches /api/health. */
export function describeConnection(value: string): string {
  const config = connectionConfig(value)
  if (config.connectionString) {
    const url = new URL(config.connectionString)
    return `postgres ${url.hostname}:${url.port || '5432'}${url.pathname}`
  }
  return `postgres ${config.host ?? '?'}:${config.port ?? 5432}/${config.database ?? '?'}`
}

/** The transaction the calling code is inside, if it is inside one. */
interface TxContext {
  /**
   * The connection the transaction holds. Every statement issued from inside
   * it goes here rather than to the pool, which is the whole of the pinning.
   */
  client: PoolClient
  depth: number
}

/**
 * `Db` over node-postgres.
 *
 * Two things this has to get right, and both were settled by what `SqliteDb`
 * had to do rather than being invented here.
 *
 * **A transaction is pinned to one connection.** A pool hands out whichever
 * connection is free, so a naive implementation would send `BEGIN` down one
 * connection, an `INSERT` down a second and `COMMIT` down a third. Postgres
 * would accept every one of them: the insert would be its own autocommitted
 * transaction, the rollback would undo nothing, and on a quiet machine where
 * the pool keeps handing back the same idle connection every test would pass.
 * So the open transaction is carried in an `AsyncLocalStorage` and `all`, `get`
 * and `run` look there before they look at the pool.
 *
 * It has to be the async context rather than a field on the class for the same
 * reason `SqliteDb` needed one: `Shelves.moveAcrossBoundary` opens a
 * transaction and then calls `remove`, which opens one of its own **through the
 * handle the class holds** rather than the one `tx` passed its work. A field
 * would also catch an unrelated request's statement and pull it into a
 * transaction that may then roll back.
 *
 * **What it does not need is `SqliteDb`'s lock.** That exists because
 * better-sqlite3 has one connection, so keeping a transaction's statements
 * contiguous meant making everything else queue behind it. Postgres has real
 * connections: an unrelated statement runs on another one, concurrently, which
 * is the point of moving to it.
 */
export class PgDb implements Db {
  private readonly context = new AsyncLocalStorage<TxContext>()

  constructor(private readonly pool: pg.Pool) {
    /*
     * An idle connection can fail with nobody waiting on it: the server is
     * restarted, a network path drops, an administrator ends the backend.
     * node-postgres reports that by emitting `error` on the pool, and an
     * `error` event with no listener is what `EventEmitter` **throws**, so the
     * default behaviour is that a blip on a connection nobody was using takes
     * the whole API process down.
     *
     * Not hypothetical, and it is how this was found: one run of the suite
     * reported db.pg.test.ts as a failed file with every test in it passing,
     * which is what an unhandled rejection outside a test looks like.
     *
     * Logged and swallowed. The pool discards the client and makes another,
     * and any request that was actually using one gets its own rejection
     * through the promise it is already awaiting.
     */
    pool.on('error', (error) => {
      console.error('[db] an idle Postgres connection failed, discarding it', error)
    })
  }

  async all<Row>(sql: string, params?: Params): Promise<Row[]> {
    const result = await this.query(sql, params)
    return result.rows as Row[]
  }

  async get<Row>(sql: string, params?: Params): Promise<Row | undefined> {
    const result = await this.query(sql, params)
    return result.rows[0] as Row | undefined
  }

  async run(sql: string, params?: Params): Promise<{ changes: number }> {
    const result = await this.query(sql, params)
    // `changes` is what the stores read and what better-sqlite3 called it.
    // `CaptureQueue.claim` decides whether a claim was taken from this number,
    // so a null read as 0 would report every successful claim as contended.
    return { changes: result.rowCount ?? 0 }
  }

  async tx<T>(work: (db: Db) => Promise<T>, options?: TxOptions): Promise<T> {
    const open = this.context.getStore()
    if (open) return this.savepoint(open, work, options)

    const client = await this.pool.connect()
    try {
      await client.query('BEGIN')
      try {
        if (options?.serialiseOn) await this.lock(client, options.serialiseOn)
        const result = await this.context.run({ client, depth: 1 }, () => work(this))
        await client.query('COMMIT')
        return result
      } catch (error) {
        await client.query('ROLLBACK')
        throw error
      }
    } finally {
      // Back to the pool whatever happened. A connection leaked here is one
      // fewer for the rest of the process, and the pool's default size is ten.
      client.release()
    }
  }

  async close(): Promise<void> {
    await this.pool.end()
  }

  /**
   * The one place a statement is sent. Inside a transaction it goes to that
   * transaction's connection; outside one it goes to the pool, which is free to
   * run it alongside anything else.
   */
  private async query(sql: string, params?: Params): Promise<pg.QueryResult> {
    // `numbered` rather than `anonymous`, and that is the whole of the dialect
    // difference in this method. Every statement in the three stores has been
    // going through this translator on SQLite since stage E, so the translation
    // itself is exercised by the entire existing suite.
    const { text, values } = bindParams(sql, params, numbered)
    const open = this.context.getStore()
    if (open) return open.client.query({ text, values })
    return this.pool.query({ text, values })
  }

  /**
   * A transaction inside a transaction, on the connection the outer one holds.
   * Postgres refuses a nested `BEGIN` with a warning and then quietly carries
   * on in the outer transaction, so the inner one's rollback would undo the
   * outer one's work. `SAVEPOINT` is the spelling that means what the caller
   * asked for, and it is the same word SQLite uses.
   */
  /**
   * Hold an exclusive lock on `name` for the length of the open transaction.
   *
   * `pg_advisory_xact_lock` rather than the session-scoped spelling, and the
   * difference matters on a pool: a session lock is released by the code that
   * took it, so a crash or a missed `finally` leaks it onto a connection the
   * pool then hands to the next request, which blocks forever on something it
   * never asked for. The transaction-scoped one is released by the COMMIT or
   * the ROLLBACK, which happen whatever the work did.
   *
   * Taken as the first statement inside BEGIN, so nothing this transaction
   * reads was read before the lock was held.
   *
   * Re-entrant: a nested transaction naming the same string re-acquires a lock
   * this transaction already owns, which Postgres counts rather than blocks on.
   */
  private async lock(client: PoolClient, name: string): Promise<void> {
    // The key is sent as text and cast, because a bigint has no JavaScript
    // number that carries it and node-postgres would otherwise send a float.
    await client.query({
      text: 'SELECT pg_advisory_xact_lock(CAST($1 AS bigint))',
      values: [lockKey(name).toString()],
    })
  }

  private async savepoint<T>(
    open: TxContext,
    work: (db: Db) => Promise<T>,
    options?: TxOptions,
  ): Promise<T> {
    const name = `bookscan_${open.depth}`
    if (options?.serialiseOn) await this.lock(open.client, options.serialiseOn)
    await open.client.query(`SAVEPOINT ${name}`)
    try {
      const result = await this.context.run(
        { client: open.client, depth: open.depth + 1 },
        () => work(this),
      )
      await open.client.query(`RELEASE SAVEPOINT ${name}`)
      return result
    } catch (error) {
      await open.client.query(`ROLLBACK TO SAVEPOINT ${name}`)
      await open.client.query(`RELEASE SAVEPOINT ${name}`)
      throw error
    }
  }
}

/**
 * Bring the schema up to date and seed it, then hand back a `Db`.
 *
 * The name and the contract are unchanged; what is underneath is not. Since
 * #172 the schema comes from the migrations rather than from `SCHEMA` above,
 * and `migrateToLatest` handles the case that makes this worth doing at all: a
 * database that already has these tables and has never been migrated is
 * **adopted**, not rebuilt. That is not hypothetical here. The Postgres
 * container has a persistent volume per checkout, so every developer already
 * has one, and so does every scratch catalogue anybody has been seeding into.
 *
 * The seeding is the same two statements db.ts runs, spelled the same way.
 * Stage D made them dialect-neutral against SQLite, which is where that was
 * cheap to prove; this is where it gets used.
 */
export async function applySchema(pool: pg.Pool): Promise<void> {
  // Straight at the pool, not through `Db.run`, and for the reason `Db` has no
  // `exec`: schema work is the only caller that wants multi-statement SQL, and
  // it is per-dialect. Drizzle's migrator wants a pool for the same reason, and
  // it is given this one rather than opening any of its own.
  await migrateToLatest(pool)

  const db = new PgDb(pool)
  const seed = `INSERT INTO shelf_ranges
       (shelf_range, start_label, start_shelf, start_area, note)
     VALUES (?, ?, ?, ?, ?)
     ON CONFLICT DO NOTHING`
  await db.run(seed, ['fiction', '1A', 1, 0, 'Starts on the first bookcase'])
  await db.run(seed, ['nonfiction', '4A', 4, 0, 'Bookcase 4 is dedicated to non-fiction'])

  // The two repairs db.ts makes to a seed written before ranges had a starting
  // bookcase. Kept for the same reason the seed is: a scratch Postgres created
  // by an older revision of this file is a database somebody may still have.
  await db.run(
    "UPDATE shelf_ranges SET start_shelf = 4, start_area = 0, start_label = '4A' " +
    "WHERE shelf_range = 'nonfiction' AND start_label = 'S4'",
  )
  await db.run(
    "UPDATE shelf_ranges SET start_label = '1A' WHERE shelf_range = 'fiction' " +
    "AND start_label != '1A'",
  )
}

/**
 * Open the catalogue on Postgres.
 *
 * Asynchronous where `openDatabase` is synchronous, which is the one thing this
 * costs the startup path: `index.ts` now awaits its database rather than having
 * it by the time the module finishes evaluating.
 */
export async function openPostgres(connectionString: string): Promise<Db> {
  const pool = new Pool(connectionConfig(connectionString))
  try {
    await applySchema(pool)
  } catch (error) {
    await pool.end()
    throw error
  }
  return new PgDb(pool)
}
