/**
 * Postgres schema and driver, the only implementation of `Db`, and still a
 * separate file from driver.ts.
 *
 * The migration chain is Drizzle's, in `web/infrastructure/db/migrations`, and
 * `applySchema` at the bottom of this file runs it. Nothing in this file decides
 * what the schema is; the constant below is what the first migration is checked
 * against.
 */

import { AsyncLocalStorage } from 'node:async_hooks'
import pg from 'pg'
import type { BookState } from '../domain/books/state'
import { migrateToLatest, type MigrationOutcome } from '../infrastructure/db/migrate'
import {
  countProjectionDisagreements, projectionDisagreements, REBUILD_COMMAND,
} from '../infrastructure/placement/projection'
import {
  countStrandedBooks, describeStranding, strandedBooks,
} from '../infrastructure/placement/stranded'
import { areaDisagreements, describeAreaDisagreement } from '../infrastructure/shelving/area-drift'
import { booksNoRuleClaims } from './claim'
import type { ShelfRange } from '../shared/shelving'
import { bindParams, lockKey, type Db, type Params, type TxOptions } from './driver'

const { Pool } = pg
type PoolClient = pg.PoolClient

/**
 * Every column keeps the type that produces the same JavaScript value the
 * SQLite schema produced, because the API contract and the React client depend
 * on it. The decisions worth arguing about are marked at the column.
 *
 * The app does not run this. The schema is created by the baseline migration
 * under `web/infrastructure/db/migrations`, and this constant is executed only by
 * `infrastructure/db/migrate.test.ts`, which builds one database from it and one
 * from the migration and diffs them, column for column, index for index and
 * constraint for constraint. So do not edit it to describe a change: a schema
 * change goes in the Drizzle schema and gets a migration, and this constant is
 * what says the conversion was faithful.
 *
 * It is also where the columns are explained. Comments do not reach the
 * catalogue, so adding one cannot move the fixed point.
 */
export const SCHEMA = `
CREATE TABLE IF NOT EXISTS books (
    -- BY DEFAULT rather than ALWAYS, so the stage H migration can insert the
    -- ids the SQLite rows already have. book_authors.book_id, captures.book_id
    -- and every cover filename on disk depend on those ids surviving.
    id                        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn13                    text    DEFAULT '',
    isbn10                    text    DEFAULT '',
    title                     text    NOT NULL,
    subtitle                  text    DEFAULT '',
    authors                   text    DEFAULT '',
    publisher                 text    DEFAULT '',
    published                 text    DEFAULT '',
    pages                     text    DEFAULT '',
    notes                     text    DEFAULT '',

    -- Derived from the book's genre tag since #223, by rangeOfGenre in
    -- domain/tagging/genre.ts, and written by the save that settled it. Every
    -- shelf query reads this.
    shelf_range               text    NOT NULL,
    -- integer, not boolean. BookRow.is_fiction is a number, the JSON contract
    -- carries 0 and 1, and the client reads them.
    --
    -- It decides nothing since #223: it is written from the settled range
    -- rather than from what the request said, so it shadows the genre tag
    -- instead of competing with it, and it goes when the client stops reading
    -- it.
    is_fiction                integer NOT NULL,
    classification_source     text    DEFAULT 'auto',
    classification_confidence text    DEFAULT 'unknown',

    -- COLLATE "C" is load-bearing on these four columns and on
    -- separators.starts_at. See the note under SORT_KEY_COLUMNS below.
    author_filing             text COLLATE "C" DEFAULT '',
    series_name               text    DEFAULT '',
    series_index              double precision,
    title_filing              text COLLATE "C" DEFAULT '',
    sort_key                  text COLLATE "C" NOT NULL,

    location                  text    DEFAULT '',
    lookup_source             text    DEFAULT '',

    -- Three photos per book: cover, back (barcode and blurb), spine.
    --
    -- **Dropped by #228, along with the seven below that describe them.** They
    -- allowed exactly one photograph of each kind, forever, so a blurred spine
    -- could only be re-shot by overwriting the original. capture is the record
    -- now: a row per photograph, and server/photographs.ts is where a filename
    -- becomes one. 0019 is where they went, and it counted every photograph
    -- they named against the rows before it dropped a thing.
    front_image               text    DEFAULT '',
    back_image                text    DEFAULT '',
    edge_image                text    DEFAULT '',
    -- The publisher's cover, fetched from the catalogue rather than
    -- photographed. Kept beside the three photos: it is what a matched book is
    -- supposed to look like, which is the thing worth comparing against.
    -- Dropped by #228; it is a catalogue photograph.
    cover_image               text    DEFAULT '',
    -- When a cover was last looked for. Set whether or not one was found, so
    -- a book with no cover anywhere is not re-fetched on every backfill.
    --
    -- **This one stays**, and it is the one judgement in #228's list: it is a
    -- fact about a search rather than about a photograph, and a book that has no
    -- artwork anywhere has been looked up and has no catalogue row to hang the
    -- stamp on.
    --
    -- text, not timestamptz, and the same goes for every _at column below.
    -- node-postgres hands a timestamptz back as a Date, which would change
    -- every JSON payload the client and the end to end suite read. ISO-8601
    -- text sorts correctly anyway, which is the only thing anything does to it.
    cover_checked_at          text,
    -- Difference hashes of the front photo and the catalogue cover, for
    -- shortlisting a book held up to the camera. See imagehash.ts.
    -- Dropped by #228: a hash is a fact about one photograph and lives on that
    -- photograph's row, which is why one can no longer sit on a book that names
    -- no photograph to rehash it from.
    front_hash                text    DEFAULT '',
    cover_hash                text    DEFAULT '',
    -- Versions of the three photos cut down to the book itself, so a view can
    -- show the book without the room around it. Separate files and separate
    -- columns, never a replacement: the photograph is the record and a crop is
    -- derived from it, so a bad crop costs nothing and can be redone. Dropped by
    -- #228; a crop is capture.crop_file, beside the photograph it was cut from.
    front_crop                text    DEFAULT '',
    back_crop                 text    DEFAULT '',
    edge_crop                 text    DEFAULT '',
    -- Which slots have been through the detector, comma separated, whether or
    -- not it found a book. A slot named here with an empty crop column was
    -- looked at and declined, which is what lets a view say "shown whole"
    -- about that photo without saying it about every photo taken before any
    -- of this existed.
    --
    -- Dropped by #228. One string per row describing three photographs could not
    -- survive a second photograph of a kind, so the distinction is
    -- capture.examined, per photograph. The wire still speaks in this string
    -- and server/photographs.ts rebuilds it from the flags.
    cropped                   text    DEFAULT '',
    isbn_source               text    DEFAULT '',
    -- Vestigial. Meant to hold the raw OCR text a capture read off a book, so
    -- a misread ISBN could be explained later without re-photographing. No
    -- client path ever wrote it (see #36), and the argument for wiring it up
    -- did not hold: the photos themselves are kept indefinitely and are the
    -- ground truth, while OCR text is a lossy, engine-version-dependent
    -- reading of them. The schema is append only, so the column stays and is
    -- always ''. Do not read or write it.
    ocr_text                  text    DEFAULT '',

    scanned_at                text    NOT NULL,
    shelved_at                text,
    -- Set while the book is physically off the shelf. A checked-out book is
    -- still catalogued but holds no position, so it neither appears as a
    -- neighbour nor takes up room in the layout.
    checked_out_at            text
);

-- Inherits sort_key's COLLATE "C", so the index and the comparisons that use
-- it cannot disagree. An index built under a different collation from the
-- query is the failure mode that reorders a shelf without erroring.
CREATE INDEX IF NOT EXISTS idx_books_shelf  ON books (shelf_range, sort_key);
CREATE INDEX IF NOT EXISTS idx_books_isbn13 ON books (isbn13);

-- Ordered authors, so "first-listed author" is unambiguous. Parsing the
-- comma-joined display string back apart is ambiguous with "Last, First".
CREATE TABLE IF NOT EXISTS book_authors (
    book_id  integer NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    position integer NOT NULL,
    name     text    NOT NULL,
    PRIMARY KEY (book_id, position)
);

-- Load-bearing. No heuristic gets Garcia Marquez and Le Guin both right.
CREATE TABLE IF NOT EXISTS author_filing (
    display_key  text PRIMARY KEY,
    filing_name  text NOT NULL,
    is_corporate integer NOT NULL DEFAULT 0,
    note         text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS shelf_ranges (
    shelf_range text    PRIMARY KEY,
    start_label text    NOT NULL,
    -- Which bookcase this range begins on. Non-fiction has its own, so both
    -- ranges laid out from bookcase 1 would give two real planks one name.
    start_shelf integer NOT NULL DEFAULT 1,
    start_area  integer NOT NULL DEFAULT 0,
    note        text    DEFAULT ''
);

-- The work queue, as it was. **Nothing reads this table since #183.**
--
-- It was deliberately separate from the books table, because that one drives
-- shelf ordering and misfile detection and letting half-identified rows into it
-- would corrupt both. The shelved_books view says that condition once instead,
-- so the separation stopped paying for itself and the queue became three states
-- a book can be in. Migration 0011 turned every row here into a book and filled
-- in book_id to say which.
--
-- The table and its rows stay, because nothing in this schema is ever dropped.
-- Do not add a reader: queued_books is the queue.
CREATE TABLE IF NOT EXISTS captures (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- pending: not yet read. ready: identified, awaiting confirmation.
    -- failed: read, but no ISBN or no catalogue match. done: became a book.
    status       text    NOT NULL DEFAULT 'pending',
    front_image  text    DEFAULT '',
    back_image   text    DEFAULT '',
    edge_image   text    DEFAULT '',
    isbn13       text    DEFAULT '',
    isbn10       text    DEFAULT '',
    isbn_source  text    DEFAULT '',
    -- The first line OCR read off the front cover, and only ever that. A
    -- title a person stated goes to edit_json and is never mirrored here, so
    -- a guess and a confirmed title cannot be mistaken for one another (#156).
    title_guess  text    DEFAULT '',
    -- Largest readable lines off the front cover, newline separated.
    cover_text   text    DEFAULT '',
    -- Which slots the worker has already read, comma separated. Photos arrive
    -- one at a time, so the worker needs to know what is new.
    analysed     text    DEFAULT '',
    -- The looked-up metadata, as a draft the review pane can load directly.
    -- Written only by the background worker. See edit_json below.
    draft_json   text    DEFAULT '',
    -- What a person stated about this book while it sat in the queue, as the
    -- subset of draft fields they actually filled in.
    --
    -- Deliberately a second column rather than an edit of draft_json. The
    -- worker owns draft_json and re-reads photographs whenever a new one
    -- arrives, so a correction stored there is one re-analysis away from being
    -- silently overwritten. Two columns means the person and the worker never
    -- write the same cell, and a capture is read as draft_json with edit_json
    -- laid over the top. See the precedence comment in queue.ts.
    edit_json    text    DEFAULT '',
    -- When a person last looked at this capture, and who. Set even by a look
    -- that changed nothing, because "nobody has been here yet" and "somebody
    -- read it and left it alone" are different facts and the queue exists to
    -- tell you which books still want attention.
    edited_by    text    DEFAULT '',
    edited_at    text,
    note         text    DEFAULT '',
    -- Soft lease, so two people cannot work the same capture at once.
    claimed_by   text    DEFAULT '',
    claimed_at   text,
    -- The same three-photos-and-a-crop arrangement books carry, and it means
    -- exactly what it means there: separate files and separate columns, never
    -- a replacement. The photograph is the record, a crop is derived from it,
    -- so a bad crop costs nothing and can be redone, and nothing on this path
    -- ever opens a photograph for writing.
    front_crop   text    DEFAULT '',
    back_crop    text    DEFAULT '',
    edge_crop    text    DEFAULT '',
    -- Which slots have been through the detector, comma separated, whether or
    -- not it found a book. Same contract as books.cropped.
    cropped      text    DEFAULT '',
    -- Frequency hash of the front photo, in the format imagehash.ts writes.
    -- The same column, the same algorithm and the same format tag as
    -- books.front_hash, so a book held up to the camera can be compared
    -- against the queue without anything comparing across two schemes. Left
    -- empty when the photo could not be hashed: a wrong match is worse than
    -- no match, so this fails closed exactly as the books path does.
    front_hash   text    DEFAULT '',
    book_id      integer REFERENCES books(id) ON DELETE SET NULL,
    created_at   text    NOT NULL,
    processed_at text
);

CREATE INDEX IF NOT EXISTS idx_captures_status ON captures (status, id);

-- Where each shelf begins.
--
-- A boundary says WHERE a shelf starts and nothing about how much it holds.
-- An earlier version stored a capacity, which is not a fact about the
-- furniture: swap a paperback for a hardback and the same shelf holds one
-- fewer. Nothing here predicts capacity. A person says when a shelf is full
-- and the boundary moves.
CREATE TABLE IF NOT EXISTS separators (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelf_range text    NOT NULL,
    -- 'shelf' ends a shelf; 'area' ends the whole bookcase and resets to
    -- shelf 1 of the next one.
    kind        text    NOT NULL DEFAULT 'shelf',
    -- Sort key of the first book on this shelf. Compared against
    -- books.sort_key, so it has to order the same way sort_key does or a
    -- boundary lands between the wrong two books.
    starts_at   text COLLATE "C" NOT NULL,
    -- Ordinal within its range: the first separator closes the first shelf.
    position    integer NOT NULL,
    note        text    DEFAULT '',
    created_at  text    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_separators ON separators (shelf_range, position);
`

/**
 * A row of `books` as the stores read it back.
 *
 * There is no photograph on it. A book's photographs are rows in `capture`, and
 * what everything above the stores actually reads is `PhotographedBook` in
 * `server/photographs.ts`: this, with the current photograph of each kind joined
 * onto it. A row of `books` cannot answer what a book looks like.
 */
export interface BookRow {
  id: number
  isbn13: string
  isbn10: string
  title: string
  subtitle: string
  authors: string
  publisher: string
  published: string
  pages: string
  notes: string
  shelf_range: ShelfRange
  classification_source: string
  classification_confidence: string
  series_name: string
  series_index: number | null
  title_filing: string
  sort_key: string
  lookup_source: string
  isbn_source: string
  /** Vestigial; always ''. See the comment on this column in SCHEMA above. */
  ocr_text: string
  scanned_at: string
  /**
   * Where the book is in its life. See `domain/books/state.ts`, and
   * `shelved_books`, which is the only relation an ordering query reads.
   *
   * It is what `Store.setCheckedOut` compares and sets, and the moment a book
   * left is the `created_at` of the `checked_out` row written in the same
   * transaction.
   *
   * `location`, `shelved_at` and `checked_out_at` are not here, because they are
   * not columns. `server/placement-ledger.ts` derives the two the wire still
   * carries, in the shape it carries them; see `PlacementFields`.
   */
  state: BookState
  /*
   * What was known about this book before anybody said what it was. Not cleared
   * when a book is shelved: what OCR read off a cover is the evidence behind the
   * title somebody typed, and `BookDetail` quotes it beside the fields. See the
   * same columns in infrastructure/db/schema.ts, where each one is explained.
   */
  /** The first line OCR read off the front cover, and never a stated title. */
  title_guess: string
  cover_text: string
  analysed: string
  /** The catalogue's answer, as JSON. The worker's channel. */
  draft_json: string
  /** What a person stated while it was queued, as JSON. The person's channel. */
  edit_json: string
  edited_by: string
  edited_at: string | null
  /** The worker's message about reading the photographs, not `notes`. */
  scan_note: string
  claimed_by: string
  claimed_at: string | null
  processed_at: string | null
  /**
   * When a cover was last looked for, found or not. A fact about a search rather
   * than about a photograph: a book with no artwork anywhere has been asked about
   * and has no `catalogue` row to carry the answer.
   */
  cover_checked_at: string | null
}

/**
 * The same row as one of the three views answers it: with the name its first
 * credit files under, which is a column `books` does not have. What a book files
 * under is a fact about the author, held on `author_alias`, and the views join it
 * back on. A lookup by id is a lookup of a book, so `Store.getBook` answers a
 * `BookRow` and `GET /api/books/:id` sends the book's credits beside it.
 *
 * Two types rather than one optional field, because the difference is which
 * relation was read. See `filed` in infrastructure/db/schema.ts, which is where
 * the join is.
 */
export interface FiledBookRow extends BookRow {
  author_filing: string
}

/**
 * The columns that must not be compared by a linguistic collation, and the
 * tables they live in.
 *
 * `Store.neighbours` seeks either side of a `sort_key` with `<` and `>`,
 * `Shelves.booksIn` orders by it, and `area.starts_at` is compared against it to
 * find where a plank begins. Every key in this catalogue is built to be compared
 * byte by byte. Postgres compares using the collation of the column, and a glibc
 * `en_US.utf8` one ignores punctuation on the first pass, folds case, and files
 * accented characters beside their unaccented forms, so two keys that ought to
 * order one way come back the other way. That does not throw: it reorders a
 * shelf, and the app then tells somebody to put a book in the wrong place.
 *
 * `sort_key` also contains `\x1f`, the unit separator that joins its components,
 * and the `.` in a padded series index, both of which are exactly the sort of
 * character a linguistic collation is entitled to treat as ignorable.
 *
 * Exported so a test can assert the declaration rather than trusting this
 * comment. See db.pg.test.ts.
 */
export const SORT_KEY_COLUMNS: readonly (readonly [table: string, column: string])[] = [
  ['books', 'sort_key'],
  ['books', 'title_filing'],
  // The filing name is the first component of every sort key a shelf is ordered
  // by, so getting its collation wrong orders almost right.
  ['author_alias', 'filing_name'],
  ['area', 'starts_at'],
]

/**
 * Turn a connection string into something node-postgres understands, in either
 * of the two spellings this app is handed one in.
 *
 * Aspire does not hand out a URL. `ConnectionStrings__bookscan` arrives as
 * ADO.NET keywords, `Host=localhost;Port=65156;Username=postgres;Password=...;
 * Database=bookscan`, and node-postgres reads only the
 * `postgres://user:pass@host:port/db` URL form and would take the whole keyword
 * string as a hostname.
 *
 * Both are accepted: a URL passes straight through, so
 * `BOOKSCAN_TEST_DATABASE_URL` and a hand-written connection still work.
 */
export function connectionConfig(value: string): pg.PoolConfig {
  const trimmed = value.trim()
  if (/^postgres(ql)?:\/\//i.test(trimmed)) return { connectionString: trimmed }

  // Walked rather than split on ';', because ADO allows a quoted value and that
  // is how a password containing a separator is spelled. Splitting first
  // truncates such a password at the separator.
  const fields = new Map<string, string>()
  let i = 0
  while (i < trimmed.length) {
    const equals = trimmed.indexOf('=', i)
    if (equals === -1) break
    const key = trimmed.slice(i, equals).trim().toLowerCase().replace(/\s+/g, '')
    i = equals + 1

    let field: string
    const quote = trimmed[i]
    if (quote === "'" || quote === '"') {
      i += 1
      field = ''
      while (i < trimmed.length) {
        if (trimmed[i] === quote) {
          // A doubled quote is an escaped one, as it is in SQL.
          if (trimmed[i + 1] === quote) { field += quote; i += 2; continue }
          i += 1
          break
        }
        field += trimmed[i]
        i += 1
      }
      const next = trimmed.indexOf(';', i)
      i = next === -1 ? trimmed.length : next + 1
    } else {
      const next = trimmed.indexOf(';', i)
      const stop = next === -1 ? trimmed.length : next
      field = trimmed.slice(i, stop).trim()
      i = stop + 1
    }

    if (key) fields.set(key, field)
  }

  const pick = (...names: string[]) => names.map((n) => fields.get(n)).find((v) => v !== undefined)

  const port = pick('port')
  return {
    // The aliases ADO.NET and Npgsql accept for the same four things. Which one
    // arrives is a property of whatever produced the string, not of this app.
    host: pick('host', 'server', 'datasource'),
    port: port ? Number(port) : undefined,
    user: pick('username', 'userid', 'user'),
    password: pick('password', 'pwd'),
    database: pick('database', 'initialcatalog'),
  }
}

/**
 * The catalogue's connection string, from the one variable it is written in.
 * `ConnectionStrings__bookscan` is the name Aspire gives it, read here so the
 * server and the maintenance scripts all find it the same way.
 *
 * Nothing else is consulted. Not `DATABASE_URL`, not `PG*`: a second accepted
 * spelling here would be a way for a shell to decide what gets written to. The
 * migration and backup tools take their target on their own command lines for the
 * same reason and do not call this.
 */
export function catalogueConnection(): string {
  const url = process.env.ConnectionStrings__bookscan ?? ''
  if (!url) {
    throw new Error(
      'No Postgres connection: ConnectionStrings__bookscan is empty. Under ' +
      'Aspire the AppHost sets it; on its own, set it to the catalogue.',
    )
  }
  return url
}

/** Host, port and database. Never the credentials: this reaches /api/health. */
export function describeConnection(value: string): string {
  const config = connectionConfig(value)
  if (config.connectionString) {
    const url = new URL(config.connectionString)
    return `postgres ${url.hostname}:${url.port || '5432'}${url.pathname}`
  }
  return `postgres ${config.host ?? '?'}:${config.port ?? 5432}/${config.database ?? '?'}`
}

/** The transaction the calling code is inside, if it is inside one. */
interface TxContext {
  /**
   * The connection the transaction holds. Every statement issued from inside
   * it goes here rather than to the pool, which is the whole of the pinning.
   */
  client: PoolClient
  depth: number
}

/**
 * `Db` over node-postgres.
 *
 * A transaction is pinned to one connection. A pool hands out whichever
 * connection is free, so a naive implementation would send `BEGIN` down one
 * connection, an `INSERT` down a second and `COMMIT` down a third. Postgres would
 * accept every one of them: the insert would be its own autocommitted
 * transaction, the rollback would undo nothing, and on a quiet machine where the
 * pool keeps handing back the same idle connection every test would pass. So the
 * open transaction is carried in an `AsyncLocalStorage` and `all`, `get` and `run`
 * look there before they look at the pool.
 *
 * It has to be the async context rather than a field on the class:
 * `Shelves.moveAcrossBoundary` opens a transaction and then calls `remove`, which
 * opens one of its own through the handle the class holds rather than the one
 * `tx` passed its work, and a field would also catch an unrelated request's
 * statement and pull it into a transaction that may then roll back.
 */
export class PgDb implements Db {
  private readonly context = new AsyncLocalStorage<TxContext>()

  constructor(private readonly pool: pg.Pool) {
    /*
     * An idle connection can fail with nobody waiting on it: the server is
     * restarted, a network path drops, an administrator ends the backend.
     * node-postgres reports that by emitting `error` on the pool, and an `error`
     * event with no listener is what `EventEmitter` throws, so the default
     * behaviour is that a blip on a connection nobody was using takes the whole
     * API process down.
     *
     * Logged and swallowed. The pool discards the client and makes another, and
     * any request that was actually using one gets its own rejection through the
     * promise it is already awaiting.
     */
    pool.on('error', (error) => {
      console.error('[db] an idle Postgres connection failed, discarding it', error)
    })
  }

  async all<Row>(sql: string, params?: Params): Promise<Row[]> {
    const result = await this.query(sql, params)
    return result.rows as Row[]
  }

  async get<Row>(sql: string, params?: Params): Promise<Row | undefined> {
    const result = await this.query(sql, params)
    return result.rows[0] as Row | undefined
  }

  async run(sql: string, params?: Params): Promise<{ changes: number }> {
    const result = await this.query(sql, params)
    // `CaptureQueue.claim` decides whether a claim was taken from this number,
    // so a null read as 0 would report every successful claim as contended.
    return { changes: result.rowCount ?? 0 }
  }

  async tx<T>(work: (db: Db) => Promise<T>, options?: TxOptions): Promise<T> {
    const open = this.context.getStore()
    if (open) return this.savepoint(open, work, options)

    const client = await this.pool.connect()
    try {
      await client.query('BEGIN')
      try {
        if (options?.serialiseOn) await this.lock(client, options.serialiseOn)
        const result = await this.context.run({ client, depth: 1 }, () => work(this))
        await client.query('COMMIT')
        return result
      } catch (error) {
        await client.query('ROLLBACK')
        throw error
      }
    } finally {
      // Back to the pool whatever happened. A connection leaked here is one
      // fewer for the rest of the process, and the pool's default size is ten.
      client.release()
    }
  }

  async close(): Promise<void> {
    await this.pool.end()
  }

  /**
   * The one place a statement is sent. Inside a transaction it goes to that
   * transaction's connection; outside one it goes to the pool, which is free to
   * run it alongside anything else.
   */
  private async query(sql: string, params?: Params): Promise<pg.QueryResult> {
    // The `?`, `@name` and `:name` placeholders the stores are written in,
    // rewritten as `$1`, `$2`.
    const { text, values } = bindParams(sql, params)
    const open = this.context.getStore()
    if (open) return open.client.query({ text, values })
    return this.pool.query({ text, values })
  }

  /**
   * A transaction inside a transaction, on the connection the outer one holds.
   * Postgres refuses a nested `BEGIN` with a warning and then quietly carries on
   * in the outer transaction, so the inner one's rollback would undo the outer
   * one's work. `SAVEPOINT` is the spelling that means what the caller asked for.
   */
  /**
   * Hold an exclusive lock on `name` for the length of the open transaction.
   *
   * `pg_advisory_xact_lock` rather than the session-scoped spelling, and the
   * difference matters on a pool: a session lock is released by the code that
   * took it, so a crash or a missed `finally` leaks it onto a connection the pool
   * then hands to the next request. The transaction-scoped one is released by the
   * COMMIT or the ROLLBACK, which happen whatever the work did.
   *
   * Taken as the first statement inside BEGIN, so nothing this transaction
   * reads was read before the lock was held.
   *
   * Re-entrant: a nested transaction naming the same string re-acquires a lock
   * this transaction already owns, which Postgres counts rather than blocks on.
   */
  private async lock(client: PoolClient, name: string): Promise<void> {
    // The key is sent as text and cast, because a bigint has no JavaScript
    // number that carries it and node-postgres would otherwise send a float.
    await client.query({
      text: 'SELECT pg_advisory_xact_lock(CAST($1 AS bigint))',
      values: [lockKey(name).toString()],
    })
  }

  private async savepoint<T>(
    open: TxContext,
    work: (db: Db) => Promise<T>,
    options?: TxOptions,
  ): Promise<T> {
    const name = `bookscan_${open.depth}`
    if (options?.serialiseOn) await this.lock(open.client, options.serialiseOn)
    await open.client.query(`SAVEPOINT ${name}`)
    try {
      const result = await this.context.run(
        { client: open.client, depth: open.depth + 1 },
        () => work(this),
      )
      await open.client.query(`RELEASE SAVEPOINT ${name}`)
      return result
    } catch (error) {
      await open.client.query(`ROLLBACK TO SAVEPOINT ${name}`)
      await open.client.query(`RELEASE SAVEPOINT ${name}`)
      throw error
    }
  }
}

/** What each migration outcome means, for the one line the app prints. */
const OUTCOMES: Record<MigrationOutcome, string> = {
  created: 'this database was empty, so the schema was created from them',
  adopted: 'this database already had the schema, so the baseline was recorded ' +
    'as applied without being run and nothing was rebuilt',
  migrated: 'this database was already under migration control',
}

/**
 * Bring the schema up to date, then hand back a `Db`.
 *
 * The schema comes from the migrations rather than from `SCHEMA` above, and
 * `migrateToLatest` handles the case that makes this worth doing at all: a
 * database that already has these tables and has never been migrated is adopted,
 * not rebuilt. That is not hypothetical, because the Postgres container has a
 * persistent volume per checkout.
 */
export async function applySchema(pool: pg.Pool): Promise<void> {
  // Straight at the pool, not through `Db.run`, and for the reason `Db` has no
  // `exec`: schema work is the only caller that wants multi-statement SQL, and it
  // is per-dialect. Drizzle's migrator is given this pool rather than opening any
  // of its own.
  const outcome = await migrateToLatest(pool)

  // Said out loud, because a database that was adopted looks exactly like one
  // that was built, right up until somebody wonders whether the tables they had
  // last week are the tables they have now.
  console.log(`[db] postgres migrations: ${OUTCOMES[outcome]}`)

  const db = new PgDb(pool)

  await sayWhetherThePlacementProjectionHolds(db)
  await sayWhetherTheFurnitureStillHasThePlanks(db)
  await sayWhetherTheRulesAgreeWithTheShelf(db)
  await sayWhetherEveryBookIsClaimed(db)
}

/**
 * Place every shelved book twice, by the shelf the app draws and by the rules,
 * and say whether the two answers are the same book for book.
 *
 * Two readings of one set of rows: the shelf takes the range off
 * `books.shelf_range` and walks a boundary list derived from the areas, and the
 * rules take no notice of that column and claim the book by the tags it carries.
 * See `infrastructure/shelving/area-drift.ts`.
 *
 * They disagree when a book's range column and its genre tags disagree, when a
 * range's run has grown past where the next range begins, and when the boundary
 * list is not the inverse of the areas it came from. Every one of those is a book
 * drawn on the wrong plank, and every one of them is silent.
 *
 * It reports, does not repair, and does not refuse to start, for the reasons
 * given above about the projection. The answer also goes to
 * `GET /api/placement/drift`, which is what the screens read; this line is what
 * `aspire logs api` shows.
 */
async function sayWhetherTheRulesAgreeWithTheShelf(db: Db): Promise<void> {
  const found = await areaDisagreements(db)
  if (!found.length) {
    console.log('[placement] every book lands where the rules claim it')
    return
  }

  // Bounded, because a line per book is not a report, it is a reason to stop
  // reading the log. The count is the number that matters.
  console.error(
    `[placement] ${found.length} books are drawn on one plank by the shelf and another ` +
    'by the rules, so the range a book files into and the rule that claims it ' +
    'no longer say the same thing. Read the names before changing anything: ' +
    found.slice(0, 10).map(describeAreaDisagreement).join('; '),
  )
}

/**
 * Say how many books no rule claims, and which of the two states each is in.
 *
 * `books.shelf_range` is written by a save and by nothing else, so a book whose
 * tag is taken off afterwards keeps the range it already had and stays exactly
 * where it is. What it becomes is a book whose position nothing can justify any
 * more: no rule claims it, so no plan will ever move it.
 *
 * A book here is either one somebody took a tag off or one nothing has ever
 * classified. The second kind has an empty `shelf_range` rather than a stale one:
 * it is in neither run, so nothing about where it sits needs justifying, and what
 * it is waiting for is a person to say which it is.
 *
 * Reported and not repaired either way, because writing a genre back would invent
 * an answer nobody gave. The question goes to `booksNoRuleClaims`, which puts it
 * to `claim`, so this line, the route and the screens say the same thing about
 * the same books by construction, and a checked out book is covered too.
 */
async function sayWhetherEveryBookIsClaimed(db: Db): Promise<void> {
  const unclaimed = await booksNoRuleClaims(db)

  if (!unclaimed.length) {
    console.log('[placement] every book in the collection is claimed by a rule')
    return
  }

  const untagged = unclaimed.filter((one) => one.why === 'untagged')

  console.error(
    `[placement] ${unclaimed.length} books no rule claims, so nothing files them: ` +
    `${untagged.length} carry no tag at all and ${unclaimed.length - untagged.length} ` +
    'carry tags no rule asks for. One that had a range keeps it and does not ' +
    'move, and one that never had one is in neither run. Say which they are, ' +
    'through the review pane or POST /api/books/:id/tags, or write a rule for ' +
    'the tags they already carry. ' +
    unclaimed.slice(0, 20).map((one) => `#${one.id} ${one.title}`).join('; '),
  )
}

/**
 * Read `books.current_area_id` back out of `book_placement` and say whether they
 * agree.
 *
 * The column is a denormalisation, asked for deliberately because drawing a shelf
 * needs every book's position at once, and a denormalisation nobody checks is a
 * second source of truth waiting to be discovered wrong. One indexed pass on
 * every start, against whatever catalogue the app has just opened.
 *
 * It reports and does not repair, and it does not refuse to start. A disagreement
 * means a writer is missing, and the evidence for which one is the disagreement
 * itself, so rebuilding on sight would erase it. `rebuildProjection` is the
 * repair, and running it is a decision somebody makes having read this line.
 *
 * This line is printed once, at startup, so a writer that stops recording at four
 * o'clock goes unreported until the next restart. `GET /api/health` asks the same
 * question live and answers `ok: false`.
 */
async function sayWhetherThePlacementProjectionHolds(db: Db): Promise<void> {
  const disagreeing = await countProjectionDisagreements(db)
  if (disagreeing === 0) {
    console.log('[placement] every book\'s current area agrees with its ledger')
    return
  }

  const named = await projectionDisagreements(db)
  console.error(
    `[placement] ${disagreeing} books have a current area their ledger does not ` +
    'agree with, so something wrote a placement without recording it. ' +
    `Find the writer first; ${REBUILD_COMMAND} folds the ledger again. ` +
    'GET /api/health answers the same question while this process runs. ' +
    named.map((one) => `#${one.bookId} ${one.title}: column ${one.projected ?? 'nowhere'}, ` +
      `ledger ${one.fromLedger ?? 'nowhere'}`).join('; '),
  )
}

/**
 * Ask the furniture whether the planks the ledger names are still on it.
 *
 * The check above compares the ledger and the column, and both can agree while
 * removing a boundary, deleting a bookcase, overflow or renumbering a piece wrote
 * to neither. This asks the one thing those writers did write to: `area.position`
 * and `fixture.position`, which neither side of that comparison derives. So the
 * projection line says whether the ledger and the column agree, and this says
 * whether what they agree on is still there.
 *
 * Reported, not repaired, and there is no repair to offer. Nothing here is
 * derived from anything here: the ledger is right about what somebody did and the
 * furniture is right about what the shelves are, so the books need a person at
 * the shelves rather than a statement.
 *
 * This line is printed once, so `GET /api/health` is the reader.
 */
async function sayWhetherTheFurnitureStillHasThePlanks(db: Db): Promise<void> {
  const stranded = await countStrandedBooks(db)
  if (stranded === 0) {
    console.log('[placement] every plank the ledger names is still on a face')
    return
  }

  const named = await strandedBooks(db)
  console.error(
    `[placement] ${stranded} books are recorded on a plank the shelves no longer ` +
    'have, so something took a piece of furniture apart and told the ledger ' +
    'nothing. Find the writer first: the books are still where somebody put ' +
    'them and only a person at the shelves can say where they go now. ' +
    'GET /api/health answers the same question while this process runs. ' +
    named.map(describeStranding).join('; '),
  )
}

export async function openPostgres(connectionString: string): Promise<Db> {
  const pool = new Pool(connectionConfig(connectionString))
  try {
    await applySchema(pool)
  } catch (error) {
    await pool.end()
    throw error
  }
  return new PgDb(pool)
}
