/**
 * Postgres schema and driver. Since stage I the only implementation of `Db`,
 * and still a separate file from driver.ts, which is what the seam was for.
 *
 * **This is the only database.** Stage G made it the default, stage H moved the
 * owner's catalogue onto it, and stage I removed `SqliteDb`, the `BOOKSCAN_DB`
 * switch and `better-sqlite3` with it. The SQLite file itself is untouched on
 * the owner's disk and is not this repository's business; the way back is a
 * `git checkout` of a commit before stage I, which brings back the driver and
 * the migration tool together.
 *
 * Three of db.ts's functions went with it and are worth naming so nobody looks
 * for them. `addMissingColumns` and `migrateSeparators` brought an old SQLite
 * catalogue file forward, and there was exactly one such file in the world;
 * `SCHEMA_VERSION` was stored in a SQLite pragma.
 *
 * Postgres has a migration chain as of #172, and it is Drizzle's, in
 * `web/infrastructure/db/migrations`. `applySchema` at the bottom of this file
 * runs it. Nothing in this file decides what the schema is any more; the
 * constant below is what the first migration is checked against.
 */

import { AsyncLocalStorage } from 'node:async_hooks'
import pg from 'pg'
import type { BookState } from '../domain/books/state'
import { migrateToLatest, type MigrationOutcome } from '../infrastructure/db/migrate'
import type { ShelfRange } from '../shared/shelving'
import { bindParams, lockKey, type Db, type Params, type TxOptions } from './driver'

const { Pool } = pg
type PoolClient = pg.PoolClient

/**
 * Every column keeps the type that produces the same JavaScript value the
 * SQLite schema produced, because the API contract and the React client depend
 * on it. The decisions worth arguing about are marked at the column.
 *
 * **The app does not run this.** Since #172 the schema is created by the
 * baseline migration under `web/infrastructure/db/migrations`, generated from
 * the Drizzle schema. It is still executed, by
 * `infrastructure/db/migrate.test.ts`, which builds one database from this
 * constant and one from the migration and diffs them, column for column, index
 * for index and constraint for constraint. A baseline that claims to reproduce
 * today's schema and is only ever compared against itself claims nothing, so
 * this constant is that test's fixed point and the reason it means anything.
 *
 * So do not edit it to describe a change. A schema change goes in the Drizzle
 * schema and gets a migration; this constant is what says the conversion was
 * faithful, and it stops being useful the moment it moves.
 *
 * **It is also where the columns are explained.** That prose lived in db.ts
 * until stage I deleted it, and the facts in it are about the product rather
 * than about SQLite: which photograph is the record, what an empty crop column
 * means, why a column nobody writes is still here. Comments do not reach the
 * catalogue, so adding one cannot move the fixed point.
 */
export const SCHEMA = `
CREATE TABLE IF NOT EXISTS books (
    -- BY DEFAULT rather than ALWAYS, so the stage H migration can insert the
    -- ids the SQLite rows already have. book_authors.book_id, captures.book_id
    -- and every cover filename on disk depend on those ids surviving.
    id                        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn13                    text    DEFAULT '',
    isbn10                    text    DEFAULT '',
    title                     text    NOT NULL,
    subtitle                  text    DEFAULT '',
    authors                   text    DEFAULT '',
    publisher                 text    DEFAULT '',
    published                 text    DEFAULT '',
    pages                     text    DEFAULT '',
    notes                     text    DEFAULT '',

    shelf_range               text    NOT NULL,
    -- integer, not boolean. BookRow.is_fiction is a number, the JSON contract
    -- carries 0 and 1, and the client reads them.
    is_fiction                integer NOT NULL,
    classification_source     text    DEFAULT 'auto',
    classification_confidence text    DEFAULT 'unknown',

    -- COLLATE "C" is load-bearing on these four columns and on
    -- separators.starts_at. See the note under SORT_KEY_COLUMNS below.
    author_filing             text COLLATE "C" DEFAULT '',
    series_name               text    DEFAULT '',
    series_index              double precision,
    title_filing              text COLLATE "C" DEFAULT '',
    sort_key                  text COLLATE "C" NOT NULL,

    location                  text    DEFAULT '',
    lookup_source             text    DEFAULT '',

    -- Three photos per book: cover, back (barcode and blurb), spine.
    front_image               text    DEFAULT '',
    back_image                text    DEFAULT '',
    edge_image                text    DEFAULT '',
    -- The publisher's cover, fetched from the catalogue rather than
    -- photographed. Kept beside the three photos: it is what a matched book is
    -- supposed to look like, which is the thing worth comparing against.
    cover_image               text    DEFAULT '',
    -- When a cover was last looked for. Set whether or not one was found, so
    -- a book with no cover anywhere is not re-fetched on every backfill.
    --
    -- text, not timestamptz, and the same goes for every _at column below.
    -- node-postgres hands a timestamptz back as a Date, which would change
    -- every JSON payload the client and the end to end suite read. ISO-8601
    -- text sorts correctly anyway, which is the only thing anything does to it.
    cover_checked_at          text,
    -- Difference hashes of the front photo and the catalogue cover, for
    -- shortlisting a book held up to the camera. See imagehash.ts.
    front_hash                text    DEFAULT '',
    cover_hash                text    DEFAULT '',
    -- Versions of the three photos cut down to the book itself, so a view can
    -- show the book without the room around it. Separate files and separate
    -- columns, never a replacement: the photograph is the record and a crop is
    -- derived from it, so a bad crop costs nothing and can be redone.
    front_crop                text    DEFAULT '',
    back_crop                 text    DEFAULT '',
    edge_crop                 text    DEFAULT '',
    -- Which slots have been through the detector, comma separated, whether or
    -- not it found a book. A slot named here with an empty crop column was
    -- looked at and declined, which is what lets a view say "shown whole"
    -- about that photo without saying it about every photo taken before any
    -- of this existed.
    cropped                   text    DEFAULT '',
    isbn_source               text    DEFAULT '',
    -- Vestigial. Meant to hold the raw OCR text a capture read off a book, so
    -- a misread ISBN could be explained later without re-photographing. No
    -- client path ever wrote it (see #36), and the argument for wiring it up
    -- did not hold: the photos themselves are kept indefinitely and are the
    -- ground truth, while OCR text is a lossy, engine-version-dependent
    -- reading of them. The schema is append only, so the column stays and is
    -- always ''. Do not read or write it.
    ocr_text                  text    DEFAULT '',

    scanned_at                text    NOT NULL,
    shelved_at                text,
    -- Set while the book is physically off the shelf. A checked-out book is
    -- still catalogued but holds no position, so it neither appears as a
    -- neighbour nor takes up room in the layout.
    checked_out_at            text
);

-- Inherits sort_key's COLLATE "C", so the index and the comparisons that use
-- it cannot disagree. An index built under a different collation from the
-- query is the failure mode that reorders a shelf without erroring.
CREATE INDEX IF NOT EXISTS idx_books_shelf  ON books (shelf_range, sort_key);
CREATE INDEX IF NOT EXISTS idx_books_isbn13 ON books (isbn13);

-- Ordered authors, so "first-listed author" is unambiguous. Parsing the
-- comma-joined display string back apart is ambiguous with "Last, First".
CREATE TABLE IF NOT EXISTS book_authors (
    book_id  integer NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    position integer NOT NULL,
    name     text    NOT NULL,
    PRIMARY KEY (book_id, position)
);

-- Load-bearing. No heuristic gets Garcia Marquez and Le Guin both right.
CREATE TABLE IF NOT EXISTS author_filing (
    display_key  text PRIMARY KEY,
    filing_name  text NOT NULL,
    is_corporate integer NOT NULL DEFAULT 0,
    note         text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS shelf_ranges (
    shelf_range text    PRIMARY KEY,
    start_label text    NOT NULL,
    -- Which bookcase this range begins on. Non-fiction has its own, so both
    -- ranges laid out from bookcase 1 would give two real planks one name.
    start_shelf integer NOT NULL DEFAULT 1,
    start_area  integer NOT NULL DEFAULT 0,
    note        text    DEFAULT ''
);

-- The work queue. A capture is three photos and nothing else until the
-- background worker has read them, which is what lets the person holding the
-- books keep moving instead of waiting on OCR.
--
-- Deliberately separate from the books table. That one drives shelf ordering
-- and misfile detection, and letting half-identified rows into it would
-- corrupt both.
CREATE TABLE IF NOT EXISTS captures (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- pending: not yet read. ready: identified, awaiting confirmation.
    -- failed: read, but no ISBN or no catalogue match. done: became a book.
    status       text    NOT NULL DEFAULT 'pending',
    front_image  text    DEFAULT '',
    back_image   text    DEFAULT '',
    edge_image   text    DEFAULT '',
    isbn13       text    DEFAULT '',
    isbn10       text    DEFAULT '',
    isbn_source  text    DEFAULT '',
    -- The first line OCR read off the front cover, and only ever that. A
    -- title a person stated goes to edit_json and is never mirrored here, so
    -- a guess and a confirmed title cannot be mistaken for one another (#156).
    title_guess  text    DEFAULT '',
    -- Largest readable lines off the front cover, newline separated.
    cover_text   text    DEFAULT '',
    -- Which slots the worker has already read, comma separated. Photos arrive
    -- one at a time, so the worker needs to know what is new.
    analysed     text    DEFAULT '',
    -- The looked-up metadata, as a draft the review pane can load directly.
    -- Written only by the background worker. See edit_json below.
    draft_json   text    DEFAULT '',
    -- What a person stated about this book while it sat in the queue, as the
    -- subset of draft fields they actually filled in.
    --
    -- Deliberately a second column rather than an edit of draft_json. The
    -- worker owns draft_json and re-reads photographs whenever a new one
    -- arrives, so a correction stored there is one re-analysis away from being
    -- silently overwritten. Two columns means the person and the worker never
    -- write the same cell, and a capture is read as draft_json with edit_json
    -- laid over the top. See the precedence comment in queue.ts.
    edit_json    text    DEFAULT '',
    -- When a person last looked at this capture, and who. Set even by a look
    -- that changed nothing, because "nobody has been here yet" and "somebody
    -- read it and left it alone" are different facts and the queue exists to
    -- tell you which books still want attention.
    edited_by    text    DEFAULT '',
    edited_at    text,
    note         text    DEFAULT '',
    -- Soft lease, so two people cannot work the same capture at once.
    claimed_by   text    DEFAULT '',
    claimed_at   text,
    -- The same three-photos-and-a-crop arrangement books carry, and it means
    -- exactly what it means there: separate files and separate columns, never
    -- a replacement. The photograph is the record, a crop is derived from it,
    -- so a bad crop costs nothing and can be redone, and nothing on this path
    -- ever opens a photograph for writing.
    front_crop   text    DEFAULT '',
    back_crop    text    DEFAULT '',
    edge_crop    text    DEFAULT '',
    -- Which slots have been through the detector, comma separated, whether or
    -- not it found a book. Same contract as books.cropped.
    cropped      text    DEFAULT '',
    -- Frequency hash of the front photo, in the format imagehash.ts writes.
    -- The same column, the same algorithm and the same format tag as
    -- books.front_hash, so a book held up to the camera can be compared
    -- against the queue without anything comparing across two schemes. Left
    -- empty when the photo could not be hashed: a wrong match is worse than
    -- no match, so this fails closed exactly as the books path does.
    front_hash   text    DEFAULT '',
    book_id      integer REFERENCES books(id) ON DELETE SET NULL,
    created_at   text    NOT NULL,
    processed_at text
);

CREATE INDEX IF NOT EXISTS idx_captures_status ON captures (status, id);

-- Where each shelf begins.
--
-- A boundary says WHERE a shelf starts and nothing about how much it holds.
-- An earlier version stored a capacity, which is not a fact about the
-- furniture: swap a paperback for a hardback and the same shelf holds one
-- fewer. Nothing here predicts capacity. A person says when a shelf is full
-- and the boundary moves.
CREATE TABLE IF NOT EXISTS separators (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelf_range text    NOT NULL,
    -- 'shelf' ends a shelf; 'area' ends the whole bookcase and resets to
    -- shelf 1 of the next one.
    kind        text    NOT NULL DEFAULT 'shelf',
    -- Sort key of the first book on this shelf. Compared against
    -- books.sort_key, so it has to order the same way sort_key does or a
    -- boundary lands between the wrong two books.
    starts_at   text COLLATE "C" NOT NULL,
    -- Ordinal within its range: the first separator closes the first shelf.
    position    integer NOT NULL,
    note        text    DEFAULT '',
    created_at  text    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_separators ON separators (shelf_range, position);
`

/**
 * A row of `books` as the stores read it back.
 *
 * Lived in db.ts until stage I, and moved here rather than into a file of its
 * own because this is where the columns it names are declared and explained.
 * It is the shape of a row, not a fact about a driver: `Store` and `Shelves`
 * both take it and neither can see what is underneath them.
 */
export interface BookRow {
  id: number
  isbn13: string
  isbn10: string
  title: string
  subtitle: string
  authors: string
  publisher: string
  published: string
  pages: string
  notes: string
  shelf_range: ShelfRange
  is_fiction: number
  classification_source: string
  classification_confidence: string
  author_filing: string
  series_name: string
  series_index: number | null
  title_filing: string
  sort_key: string
  location: string
  lookup_source: string
  front_image: string
  back_image: string
  edge_image: string
  isbn_source: string
  /** Vestigial; always ''. See the comment on this column in SCHEMA above. */
  ocr_text: string
  scanned_at: string
  shelved_at: string | null
  /** ISO timestamp while the book is off the shelf, null while it is on one. */
  checked_out_at: string | null
  /**
   * Where the book is in its life. See `domain/books/state.ts`, and
   * `shelved_books`, which is the only relation an ordering query reads.
   *
   * Added beside `checked_out_at` rather than instead of it (#183). That column
   * is still what the client reads and what `Store.setCheckedOut` compares and
   * sets, and the two are written in one statement so they cannot disagree.
   */
  state: BookState
  /** Publisher cover from the catalogue, as a filename under /api/covers. */
  cover_image: string
  /** When a cover was last looked for, found or not. */
  cover_checked_at: string | null
  /** Difference hashes, for matching a book held up to the camera. */
  front_hash: string
  cover_hash: string
  /**
   * The three photos cut to the book, as filenames under /api/covers. Empty
   * where the detector was never run or could not find the book.
   */
  front_crop: string
  back_crop: string
  edge_crop: string
  /** Slots the detector has looked at, comma separated. See SCHEMA above. */
  cropped: string
}

/**
 * The columns that must not be compared by a linguistic collation, and the
 * tables they live in.
 *
 * `sort_key` is the spine of the product. `Store.neighbours` seeks either side
 * of one with `<` and `>`, `Shelves.booksIn` orders by it, and
 * `separators.starts_at` is compared against it to find where a shelf begins.
 * Every key in this catalogue was built to be compared byte by byte, which is
 * what the SQLite this app grew up on did with no exceptions. Postgres compares
 * using the collation of the column, and a glibc `en_US.utf8` one ignores
 * punctuation on the first pass, folds case, and files accented characters
 * beside their unaccented forms. Two keys that ought to order one way come back
 * the other way.
 *
 * That does not throw and does not fail a smoke test. It reorders a shelf, or
 * moves one book past a separator, and the app then tells somebody to put a
 * book in the wrong place.
 *
 * `sort_key` also contains `\x1f`, the unit separator that joins its
 * components, and the `.` in a padded series index, both of which are exactly
 * the sort of character a linguistic collation is entitled to treat as
 * ignorable.
 *
 * Exported so a test can assert the declaration rather than trusting this
 * comment. See db.pg.test.ts, which reads the collation back out of the
 * catalogue and also shows the fixture coming out in the wrong order without it.
 */
export const SORT_KEY_COLUMNS: readonly (readonly [table: string, column: string])[] = [
  ['books', 'sort_key'],
  ['books', 'author_filing'],
  ['books', 'title_filing'],
  ['separators', 'starts_at'],
]

/**
 * Turn a connection string into something node-postgres understands, in either
 * of the two spellings this app is handed one in.
 *
 * **Aspire does not hand out a URL.** `ConnectionStrings__bookscan` arrives as
 * ADO.NET keywords, `Host=localhost;Port=65156;Username=postgres;Password=...;
 * Database=bookscan`, because the connection string is produced for the .NET
 * clients Aspire was built around. node-postgres reads only the
 * `postgres://user:pass@host:port/db` URL form and would take the whole
 * keyword string as a hostname. The plan said to read the variable the way
 * `PORT` is read, which is true of getting it and not of using it.
 *
 * Both are accepted: a URL passes straight through, so
 * `BOOKSCAN_TEST_DATABASE_URL` and a hand-written connection still work.
 */
export function connectionConfig(value: string): pg.PoolConfig {
  const trimmed = value.trim()
  if (/^postgres(ql)?:\/\//i.test(trimmed)) return { connectionString: trimmed }

  // Walked rather than split on ';', because ADO allows a quoted value and
  // that is how a password containing a separator is spelled. Splitting first
  // truncates such a password at the separator, which surfaces as an
  // authentication failure that says nothing about the string being cut.
  const fields = new Map<string, string>()
  let i = 0
  while (i < trimmed.length) {
    const equals = trimmed.indexOf('=', i)
    if (equals === -1) break
    const key = trimmed.slice(i, equals).trim().toLowerCase().replace(/\s+/g, '')
    i = equals + 1

    let field: string
    const quote = trimmed[i]
    if (quote === "'" || quote === '"') {
      i += 1
      field = ''
      while (i < trimmed.length) {
        if (trimmed[i] === quote) {
          // A doubled quote is an escaped one, as it is in SQL.
          if (trimmed[i + 1] === quote) { field += quote; i += 2; continue }
          i += 1
          break
        }
        field += trimmed[i]
        i += 1
      }
      const next = trimmed.indexOf(';', i)
      i = next === -1 ? trimmed.length : next + 1
    } else {
      const next = trimmed.indexOf(';', i)
      const stop = next === -1 ? trimmed.length : next
      field = trimmed.slice(i, stop).trim()
      i = stop + 1
    }

    if (key) fields.set(key, field)
  }

  const pick = (...names: string[]) => names.map((n) => fields.get(n)).find((v) => v !== undefined)

  const port = pick('port')
  return {
    // The aliases ADO.NET and Npgsql accept for the same four things. Listed
    // rather than assumed, because which one arrives is a property of whatever
    // produced the string and not of this app.
    host: pick('host', 'server', 'datasource'),
    port: port ? Number(port) : undefined,
    user: pick('username', 'userid', 'user'),
    password: pick('password', 'pwd'),
    database: pick('database', 'initialcatalog'),
  }
}

/**
 * The catalogue's connection string, from the one variable it is written in.
 *
 * `ConnectionStrings__bookscan` is the name Aspire gives it. Read here so the
 * server and the three maintenance scripts that open the catalogue by hand all
 * find it the same way, and so "there is exactly one name" is a fact about one
 * function rather than about four call sites that currently agree.
 *
 * Nothing else is consulted. Not `DATABASE_URL`, not `PG*`: the test harness
 * ignores every ambient connection variable for a reason (server/testdb.ts),
 * and a second accepted spelling here would be a way for a shell to decide what
 * gets written to. The migration and backup tools take their target on their
 * own command lines for the same reason and do not call this.
 */
export function catalogueConnection(): string {
  const url = process.env.ConnectionStrings__bookscan ?? ''
  if (!url) {
    throw new Error(
      'No Postgres connection: ConnectionStrings__bookscan is empty. Under ' +
      'Aspire the AppHost sets it; on its own, set it to the catalogue.',
    )
  }
  return url
}

/** Host, port and database. Never the credentials: this reaches /api/health. */
export function describeConnection(value: string): string {
  const config = connectionConfig(value)
  if (config.connectionString) {
    const url = new URL(config.connectionString)
    return `postgres ${url.hostname}:${url.port || '5432'}${url.pathname}`
  }
  return `postgres ${config.host ?? '?'}:${config.port ?? 5432}/${config.database ?? '?'}`
}

/** The transaction the calling code is inside, if it is inside one. */
interface TxContext {
  /**
   * The connection the transaction holds. Every statement issued from inside
   * it goes here rather than to the pool, which is the whole of the pinning.
   */
  client: PoolClient
  depth: number
}

/**
 * `Db` over node-postgres.
 *
 * Two things this has to get right, and both were settled by what `SqliteDb`
 * had to do rather than being invented here.
 *
 * **A transaction is pinned to one connection.** A pool hands out whichever
 * connection is free, so a naive implementation would send `BEGIN` down one
 * connection, an `INSERT` down a second and `COMMIT` down a third. Postgres
 * would accept every one of them: the insert would be its own autocommitted
 * transaction, the rollback would undo nothing, and on a quiet machine where
 * the pool keeps handing back the same idle connection every test would pass.
 * So the open transaction is carried in an `AsyncLocalStorage` and `all`, `get`
 * and `run` look there before they look at the pool.
 *
 * It has to be the async context rather than a field on the class for the same
 * reason `SqliteDb` needed one: `Shelves.moveAcrossBoundary` opens a
 * transaction and then calls `remove`, which opens one of its own **through the
 * handle the class holds** rather than the one `tx` passed its work. A field
 * would also catch an unrelated request's statement and pull it into a
 * transaction that may then roll back.
 *
 * **What it does not need is `SqliteDb`'s lock.** That exists because
 * better-sqlite3 has one connection, so keeping a transaction's statements
 * contiguous meant making everything else queue behind it. Postgres has real
 * connections: an unrelated statement runs on another one, concurrently, which
 * is the point of moving to it.
 */
export class PgDb implements Db {
  private readonly context = new AsyncLocalStorage<TxContext>()

  constructor(private readonly pool: pg.Pool) {
    /*
     * An idle connection can fail with nobody waiting on it: the server is
     * restarted, a network path drops, an administrator ends the backend.
     * node-postgres reports that by emitting `error` on the pool, and an
     * `error` event with no listener is what `EventEmitter` **throws**, so the
     * default behaviour is that a blip on a connection nobody was using takes
     * the whole API process down.
     *
     * Not hypothetical, and it is how this was found: one run of the suite
     * reported db.pg.test.ts as a failed file with every test in it passing,
     * which is what an unhandled rejection outside a test looks like.
     *
     * Logged and swallowed. The pool discards the client and makes another,
     * and any request that was actually using one gets its own rejection
     * through the promise it is already awaiting.
     */
    pool.on('error', (error) => {
      console.error('[db] an idle Postgres connection failed, discarding it', error)
    })
  }

  async all<Row>(sql: string, params?: Params): Promise<Row[]> {
    const result = await this.query(sql, params)
    return result.rows as Row[]
  }

  async get<Row>(sql: string, params?: Params): Promise<Row | undefined> {
    const result = await this.query(sql, params)
    return result.rows[0] as Row | undefined
  }

  async run(sql: string, params?: Params): Promise<{ changes: number }> {
    const result = await this.query(sql, params)
    // `changes` is what the stores read and what better-sqlite3 called it.
    // `CaptureQueue.claim` decides whether a claim was taken from this number,
    // so a null read as 0 would report every successful claim as contended.
    return { changes: result.rowCount ?? 0 }
  }

  async tx<T>(work: (db: Db) => Promise<T>, options?: TxOptions): Promise<T> {
    const open = this.context.getStore()
    if (open) return this.savepoint(open, work, options)

    const client = await this.pool.connect()
    try {
      await client.query('BEGIN')
      try {
        if (options?.serialiseOn) await this.lock(client, options.serialiseOn)
        const result = await this.context.run({ client, depth: 1 }, () => work(this))
        await client.query('COMMIT')
        return result
      } catch (error) {
        await client.query('ROLLBACK')
        throw error
      }
    } finally {
      // Back to the pool whatever happened. A connection leaked here is one
      // fewer for the rest of the process, and the pool's default size is ten.
      client.release()
    }
  }

  async close(): Promise<void> {
    await this.pool.end()
  }

  /**
   * The one place a statement is sent. Inside a transaction it goes to that
   * transaction's connection; outside one it goes to the pool, which is free to
   * run it alongside anything else.
   */
  private async query(sql: string, params?: Params): Promise<pg.QueryResult> {
    // The `?`, `@name` and `:name` placeholders the stores are written in,
    // rewritten as `$1`, `$2`. Stage E routed SQLite through this same
    // translator so it was exercised by the whole suite a stage before this
    // driver existed; the suite exercises it here now for the same reason.
    const { text, values } = bindParams(sql, params)
    const open = this.context.getStore()
    if (open) return open.client.query({ text, values })
    return this.pool.query({ text, values })
  }

  /**
   * A transaction inside a transaction, on the connection the outer one holds.
   * Postgres refuses a nested `BEGIN` with a warning and then quietly carries
   * on in the outer transaction, so the inner one's rollback would undo the
   * outer one's work. `SAVEPOINT` is the spelling that means what the caller
   * asked for, and it is the same word SQLite uses.
   */
  /**
   * Hold an exclusive lock on `name` for the length of the open transaction.
   *
   * `pg_advisory_xact_lock` rather than the session-scoped spelling, and the
   * difference matters on a pool: a session lock is released by the code that
   * took it, so a crash or a missed `finally` leaks it onto a connection the
   * pool then hands to the next request, which blocks forever on something it
   * never asked for. The transaction-scoped one is released by the COMMIT or
   * the ROLLBACK, which happen whatever the work did.
   *
   * Taken as the first statement inside BEGIN, so nothing this transaction
   * reads was read before the lock was held.
   *
   * Re-entrant: a nested transaction naming the same string re-acquires a lock
   * this transaction already owns, which Postgres counts rather than blocks on.
   */
  private async lock(client: PoolClient, name: string): Promise<void> {
    // The key is sent as text and cast, because a bigint has no JavaScript
    // number that carries it and node-postgres would otherwise send a float.
    await client.query({
      text: 'SELECT pg_advisory_xact_lock(CAST($1 AS bigint))',
      values: [lockKey(name).toString()],
    })
  }

  private async savepoint<T>(
    open: TxContext,
    work: (db: Db) => Promise<T>,
    options?: TxOptions,
  ): Promise<T> {
    const name = `bookscan_${open.depth}`
    if (options?.serialiseOn) await this.lock(open.client, options.serialiseOn)
    await open.client.query(`SAVEPOINT ${name}`)
    try {
      const result = await this.context.run(
        { client: open.client, depth: open.depth + 1 },
        () => work(this),
      )
      await open.client.query(`RELEASE SAVEPOINT ${name}`)
      return result
    } catch (error) {
      await open.client.query(`ROLLBACK TO SAVEPOINT ${name}`)
      await open.client.query(`RELEASE SAVEPOINT ${name}`)
      throw error
    }
  }
}

/** What each migration outcome means, for the one line the app prints. */
const OUTCOMES: Record<MigrationOutcome, string> = {
  created: 'this database was empty, so the schema was created from them',
  adopted: 'this database already had the schema, so the baseline was recorded ' +
    'as applied without being run and nothing was rebuilt',
  migrated: 'this database was already under migration control',
}

/**
 * Bring the schema up to date and seed it, then hand back a `Db`.
 *
 * The name and the contract are unchanged; what is underneath is not. Since
 * #172 the schema comes from the migrations rather than from `SCHEMA` above,
 * and `migrateToLatest` handles the case that makes this worth doing at all: a
 * database that already has these tables and has never been migrated is
 * **adopted**, not rebuilt. That is not hypothetical here. The Postgres
 * container has a persistent volume per checkout, so every developer already
 * has one, and so does every scratch catalogue anybody has been seeding into.
 *
 * The two seed statements were made dialect-neutral in stage D, against SQLite,
 * where that was cheap to prove. This is where they are run.
 */
export async function applySchema(pool: pg.Pool): Promise<void> {
  // Straight at the pool, not through `Db.run`, and for the reason `Db` has no
  // `exec`: schema work is the only caller that wants multi-statement SQL, and
  // it is per-dialect. Drizzle's migrator wants a pool for the same reason, and
  // it is given this one rather than opening any of its own.
  const outcome = await migrateToLatest(pool)

  // Said out loud, because the interesting outcomes are the quiet ones. A
  // database that was adopted looks exactly like one that was built, right up
  // until somebody wonders whether the tables they had last week are the tables
  // they have now. `aspire logs api` is where this shows up.
  console.log(`[db] postgres migrations: ${OUTCOMES[outcome]}`)

  const db = new PgDb(pool)
  const seed = `INSERT INTO shelf_ranges
       (shelf_range, start_label, start_shelf, start_area, note)
     VALUES (?, ?, ?, ?, ?)
     ON CONFLICT DO NOTHING`
  await db.run(seed, ['fiction', '1A', 1, 0, 'Starts on the first bookcase'])
  await db.run(seed, ['nonfiction', '4A', 4, 0, 'Bookcase 4 is dedicated to non-fiction'])

  // Two repairs to a seed written before ranges had a starting bookcase. Kept
  // for the same reason the seed is: a scratch Postgres created by an older
  // revision of this file is a database somebody may still have.
  await db.run(
    "UPDATE shelf_ranges SET start_shelf = 4, start_area = 0, start_label = '4A' " +
    "WHERE shelf_range = 'nonfiction' AND start_label = 'S4'",
  )
  await db.run(
    "UPDATE shelf_ranges SET start_label = '1A' WHERE shelf_range = 'fiction' " +
    "AND start_label != '1A'",
  )
}

/**
 * Open the catalogue on Postgres.
 *
 * Asynchronous, where opening a SQLite file was not, which is the one thing the
 * move cost the startup path: `index.ts` awaits its database rather than having
 * it by the time the module finishes evaluating.
 */
export async function openPostgres(connectionString: string): Promise<Db> {
  const pool = new Pool(connectionConfig(connectionString))
  try {
    await applySchema(pool)
  } catch (error) {
    await pool.end()
    throw error
  }
  return new PgDb(pool)
}
