/**
 * Stage H: move a SQLite catalogue into Postgres, and prove it arrived intact.
 *
 * The copy is the easy half and it is not what this file is for. Anybody can
 * move rows; the only thing that makes moving somebody's irreplaceable
 * catalogue safe is being able to demonstrate afterwards that nothing changed.
 * So `verifyCatalogue` is the deliverable and `migrateCatalogue` is what it
 * checks, and the two are deliberately independent: the verification re-reads
 * both databases from scratch and shares no code with the writer beyond the
 * list of tables.
 *
 * What is proved, and why each one is here:
 *
 * - **Every row of every table, compared cell by cell.** Counts agreeing is
 *   necessary and nowhere near sufficient: 197 rows of the wrong content is
 *   still 197 rows. A digest per table is emitted as well, so the acceptance
 *   check the operator writes down is one number per table rather than a wall
 *   of output they skim.
 * - **The type of every cell**, not only its value. `pg` hands `bigint` and
 *   `numeric` back as JavaScript strings, an empty string is one round trip
 *   away from becoming NULL, and both read as "the data is all there" until
 *   something does arithmetic or asks whether a column is set. `''` and `NULL`
 *   are a documented, load-bearing distinction in the crop columns (see db.ts:
 *   a slot named in `cropped` whose crop column is `''` was examined and
 *   declined, which is a different fact from never having been looked at).
 * - **The shelf order, position by position.** This is the one most likely to
 *   be quietly wrong. `sort_key` is joined with `\x1f` and carries a `.` in the
 *   padded series index, exactly the characters a linguistic collation is
 *   entitled to treat as ignorable, and the entire product is `ORDER BY
 *   sort_key`. It is compared as an ordered list out of both databases, with a
 *   negative control: the same rows ordered under the database's own collation,
 *   which must come back *different* or the check proved nothing.
 * - **Where each shelf begins.** `separators.starts_at` is compared against
 *   `books.sort_key` to find boundaries, so the boundary is resolved on both
 *   sides and the answers compared. An ordering difference small enough to
 *   leave the list identical but move one book past a divider would show here.
 * - **The covers still resolve.** The database holds bare filenames joined
 *   against the data directory at read time, so a migrated row pointing at a
 *   file that is not there is a book with no photographs.
 * - **The next insert does not collide.** Ids are carried across explicitly,
 *   which is what `GENERATED BY DEFAULT AS IDENTITY` is for, and an identity
 *   sequence that was never restarted hands out 1 on the next scan. Everything
 *   looks perfect until then.
 *
 * Nothing here writes to the source. The CLI opens it read-only and this module
 * only ever issues SELECTs against it.
 */

import { createHash } from 'node:crypto'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import type { Db } from './driver'

/** A table to carry across, and how to order it so a comparison is stable. */
export interface TableSpec {
  table: string
  /**
   * Columns that order the table deterministically on both sides. Not
   * `sort_key`: the comparison must not depend on the very thing it is
   * checking, and a tie there would order rows differently on each side for
   * reasons that are nobody's bug.
   */
  key: readonly string[]
  /** Tables whose `id` comes from an identity sequence that has to be restarted. */
  identity?: boolean
}

/**
 * The six tables, in an order that satisfies the foreign keys: `book_authors`
 * and `captures` both reference `books`.
 */
export const TABLES: readonly TableSpec[] = [
  { table: 'shelf_ranges', key: ['shelf_range'] },
  { table: 'author_filing', key: ['display_key'] },
  { table: 'books', key: ['id'], identity: true },
  { table: 'book_authors', key: ['book_id', 'position'] },
  { table: 'captures', key: ['id'], identity: true },
  { table: 'separators', key: ['id'], identity: true },
]

/**
 * The tables a target has to be empty of before this will write to it.
 *
 * `shelf_ranges` is not among them, and cannot be: `applySchema` seeds it, so a
 * freshly created Postgres catalogue already has two rows in it. The source's
 * copy of that table is carried across as an upsert instead.
 */
const DATA_TABLES = ['books', 'book_authors', 'captures', 'separators', 'author_filing'] as const

/**
 * Columns holding a cover filename, joined against the data directory at read
 * time. Listed rather than guessed from the name, because `cover_hash` and
 * `front_hash` end in nothing that distinguishes them from a filename.
 */
export const IMAGE_COLUMNS: Readonly<Record<string, readonly string[]>> = {
  books: ['front_image', 'back_image', 'edge_image', 'cover_image',
          'front_crop', 'back_crop', 'edge_crop'],
  captures: ['front_image', 'back_image', 'edge_image',
             'front_crop', 'back_crop', 'edge_crop'],
}

/**
 * The four columns whose ordering the product depends on. The same list
 * `db.pg.ts` declares `COLLATE "C"` on, repeated here because this is where it
 * is checked against a real catalogue rather than a fixture.
 */
const COLLATED_COLUMNS: readonly (readonly [string, string])[] = [
  ['books', 'sort_key'],
  ['books', 'author_filing'],
  ['books', 'title_filing'],
  ['separators', 'starts_at'],
]

/**
 * Postgres refuses more than 65535 parameters in one statement, and a 37 column
 * insert reaches that at 1770 rows. Kept well under it, and small enough that a
 * failure names a batch a person can look at.
 */
const BATCH_ROWS = 200

export type Row = Record<string, unknown>

export interface Note { (line: string): void }

/** What a column looks like on one side, for the coercion comparison. */
export interface ColumnProfile {
  column: string
  nulls: number
  empties: number
  /** Distinct JavaScript types seen, sorted. `null` is reported separately. */
  types: string[]
}

export interface TableComparison {
  table: string
  sourceRows: number
  targetRows: number
  cells: number
  /** Every difference found, cell by cell. Capped only by the caller reading it. */
  mismatches: string[]
  sourceDigest: string
  targetDigest: string
  columns: { source: ColumnProfile; target: ColumnProfile }[]
}

export interface OrderingCheck {
  /** Book ids read out of each side in `ORDER BY sort_key, id`. */
  sourceOrder: number[]
  targetOrder: number[]
  /** Positions at which the two disagree. Empty is the pass. */
  disagreements: number[]
  /** Books sharing a sort key, which is why the comparison also orders by id. */
  duplicateKeys: string[]
  /** The target database's own collation, for the negative control below. */
  databaseCollation: string
  /** False when the target is a byte order database and the control is vacuous. */
  collationIsLinguistic: boolean
  /**
   * The same rows ordered under the database's own collation instead of the
   * column's `COLLATE "C"`. Different means the check above discriminates.
   */
  controlDisagreements: number
  controlExample: string | null
  /** What the catalogue says each collated column was actually declared as. */
  declaredCollations: { table: string; column: string; collation: string }[]
  /** Where each shelf begins, resolved on both sides. */
  boundaries: { separator: number; range: string; sourceFirstBook: number | null;
                targetFirstBook: number | null }[]
  boundaryDisagreements: number
}

export interface CoverCheck {
  directory: string
  /** Distinct filenames referenced by the migrated rows. */
  referenced: number
  present: number
  missing: string[]
}

export interface SequenceCheck {
  table: string
  maxId: number | null
  nextId: number
  ok: boolean
}

export interface VerifyReport {
  tables: TableComparison[]
  ordering: OrderingCheck
  covers: CoverCheck | null
  sequences: SequenceCheck[]
  /** Everything that has to be true, and is not. Empty is the pass. */
  problems: string[]
  elapsedMs: number
}

export interface MigrateResult {
  /** Rows read out of the source, per table. */
  read: Record<string, number>
  /** Rows the target reported writing, per table. */
  written: Record<string, number>
  sequences: { table: string; restartedAt: number }[]
  elapsedMs: number
}

/* ------------------------------------------------------------------ *
 * Introspection. Two dialects, because this tool is by definition the
 * one thing in the codebase that talks to both at once.
 * ------------------------------------------------------------------ */

/** Column names of a SQLite table, in declaration order. */
export async function sourceColumns(source: Db, table: string): Promise<string[]> {
  // Table names come from TABLES above, never from input.
  const rows = await source.all<{ name: string }>(`PRAGMA table_info("${table}")`)
  return rows.map((r) => r.name)
}

/** Column names of a Postgres table, in declaration order. */
export async function targetColumns(target: Db, table: string): Promise<string[]> {
  const rows = await target.all<{ column_name: string }>(
    `SELECT column_name FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ?
      ORDER BY ordinal_position`,
    [table],
  )
  return rows.map((r) => r.column_name)
}

/**
 * Refuse to run unless both sides agree on every column of every table.
 *
 * A column in the source and not the target would be silently dropped, which is
 * the failure this whole stage exists to make impossible. A column in the target
 * and not the source means the source was not brought forward by the SQLite code
 * path first, and the rows would arrive carrying a default nobody chose.
 */
export async function checkSchemas(source: Db, target: Db): Promise<string[]> {
  const problems: string[] = []
  for (const { table } of TABLES) {
    const from = await sourceColumns(source, table)
    const to = await targetColumns(target, table)
    if (from.length === 0) { problems.push(`the source has no table ${table}`); continue }
    if (to.length === 0) { problems.push(`the target has no table ${table}`); continue }

    const missingInTarget = from.filter((c) => !to.includes(c))
    const missingInSource = to.filter((c) => !from.includes(c))
    if (missingInTarget.length) {
      problems.push(
        `${table}: the source has columns the target does not, which would be ` +
        `dropped: ${missingInTarget.join(', ')}`,
      )
    }
    if (missingInSource.length) {
      problems.push(
        `${table}: the target has columns the source does not: ` +
        `${missingInSource.join(', ')}. Open the source once with the SQLite ` +
        `code path so addMissingColumns brings it forward, then snapshot it again.`,
      )
    }
  }
  return problems
}

export async function countRows(db: Db, table: string): Promise<number> {
  const row = await db.get<{ n: number }>(`SELECT CAST(COUNT(*) AS INTEGER) AS n FROM "${table}"`)
  return Number(row?.n ?? 0)
}

/** Whether the target holds a catalogue already. `shelf_ranges` does not count. */
export async function targetHoldsData(target: Db): Promise<Record<string, number>> {
  const held: Record<string, number> = {}
  for (const table of DATA_TABLES) {
    const n = await countRows(target, table)
    if (n > 0) held[table] = n
  }
  return held
}

/* ------------------------------------------------------------------ *
 * The copy.
 * ------------------------------------------------------------------ */

function quoted(columns: readonly string[]): string {
  return columns.map((c) => `"${c}"`).join(', ')
}

async function readAll(db: Db, table: string, columns: readonly string[],
                       key: readonly string[]): Promise<Row[]> {
  return db.all<Row>(
    `SELECT ${quoted(columns)} FROM "${table}" ORDER BY ${quoted(key)}`,
  )
}

/**
 * Copy every table from `source` into `target`, in one transaction.
 *
 * One transaction is what makes a half-finished run harmless: a failure at any
 * point rolls the whole thing back, so the target is either the catalogue or
 * untouched, and re-running needs no cleanup. `--force` truncates first, inside
 * the same transaction, so even a re-run over a populated target is atomic.
 */
export async function migrateCatalogue(
  source: Db,
  target: Db,
  options: { force?: boolean; onNote?: Note } = {},
): Promise<MigrateResult> {
  const note = options.onNote ?? (() => {})
  const started = Date.now()
  const read: Record<string, number> = {}
  const written: Record<string, number> = {}
  const sequences: { table: string; restartedAt: number }[] = []

  await target.tx(async (db) => {
    if (options.force) {
      // RESTART IDENTITY so a forced re-run starts from the same place a fresh
      // database would, and CASCADE because book_authors and captures point at
      // books. shelf_ranges is upserted below rather than emptied.
      await db.run(
        'TRUNCATE books, book_authors, captures, separators, author_filing ' +
        'RESTART IDENTITY CASCADE',
      )
      note('emptied the target (--force)')
    }

    for (const { table, key } of TABLES) {
      const columns = await sourceColumns(source, table)
      const rows = await readAll(source, table, columns, key)
      read[table] = rows.length
      written[table] = 0

      // The source is the authority on shelf_ranges and applySchema has already
      // seeded two rows, so this one merges rather than inserting.
      const conflict = table === 'shelf_ranges'
        ? ` ON CONFLICT (shelf_range) DO UPDATE SET ` +
          columns.filter((c) => c !== 'shelf_range')
            .map((c) => `"${c}" = EXCLUDED."${c}"`).join(', ')
        : ''

      for (let at = 0; at < rows.length; at += BATCH_ROWS) {
        const batch = rows.slice(at, at + BATCH_ROWS)
        const tuple = `(${columns.map(() => '?').join(', ')})`
        const values: unknown[] = []
        for (const row of batch) {
          for (const column of columns) values.push(row[column] ?? null)
        }
        // Every column is named and every value is passed explicitly, including
        // the nulls. Leaving a column out would take the schema default, which
        // is how a NULL that meant "never looked at" becomes an empty string
        // that means "looked at and declined".
        const result = await db.run(
          `INSERT INTO "${table}" (${quoted(columns)}) VALUES ` +
          batch.map(() => tuple).join(', ') + conflict,
          values,
        )
        written[table] += result.changes
      }
      note(`${table.padEnd(14)} ${String(rows.length).padStart(6)} rows`)
    }

    // The classic failure: everything looks perfect until the next scan
    // collides on a primary key. Identity columns do not notice ids that were
    // inserted explicitly, so the sequence has to be told where the data ends.
    for (const { table, identity } of TABLES) {
      if (!identity) continue
      const row = await db.get<{ max: number | null }>(
        `SELECT MAX(id) AS max FROM "${table}"`,
      )
      const next = Number(row?.max ?? 0) + 1
      await db.run(`ALTER TABLE "${table}" ALTER COLUMN id RESTART WITH ${next}`)
      sequences.push({ table, restartedAt: next })
      note(`${table.padEnd(14)} next id ${next}`)
    }
  })

  return { read, written, sequences, elapsedMs: Date.now() - started }
}

/* ------------------------------------------------------------------ *
 * The verification.
 * ------------------------------------------------------------------ */

/**
 * One cell, written so that a difference of type is a difference of text.
 *
 * `null`, `''` and `0` have to be three different strings here or the digest
 * agrees across exactly the coercions this is looking for, and a number that
 * arrived as the string "197" has to differ from the number 197.
 */
function cell(value: unknown): string {
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'number') return `num:${Object.is(value, -0) ? '-0' : String(value)}`
  if (typeof value === 'string') return `str:${JSON.stringify(value)}`
  if (typeof value === 'boolean') return `bool:${value}`
  if (typeof value === 'bigint') return `bigint:${value}`
  if (value instanceof Date) return `date:${value.toISOString()}`
  if (value instanceof Uint8Array) return `bytes:${Buffer.from(value).toString('hex')}`
  return `${typeof value}:${JSON.stringify(value)}`
}

function digest(rows: Row[], columns: readonly string[]): string {
  const hash = createHash('sha256')
  for (const row of rows) {
    hash.update(columns.map((c) => cell(row[c])).join('\x1f'))
    hash.update('\n')
  }
  return hash.digest('hex').slice(0, 16)
}

function profile(rows: Row[], column: string): ColumnProfile {
  let nulls = 0
  let empties = 0
  const types = new Set<string>()
  for (const row of rows) {
    const value = row[column]
    if (value === null || value === undefined) { nulls += 1; continue }
    if (value === '') empties += 1
    types.add(typeof value)
  }
  return { column, nulls, empties, types: [...types].sort() }
}

async function compareTable(source: Db, target: Db, spec: TableSpec): Promise<TableComparison> {
  const columns = await sourceColumns(source, spec.table)
  const from = await readAll(source, spec.table, columns, spec.key)
  const to = await readAll(target, spec.table, columns, spec.key)

  const mismatches: string[] = []
  const rows = Math.min(from.length, to.length)
  for (let i = 0; i < rows; i += 1) {
    const left = from[i] as Row
    const right = to[i] as Row
    for (const column of columns) {
      const a = cell(left[column])
      const b = cell(right[column])
      if (a !== b) {
        const where = spec.key.map((k) => `${k}=${String(left[k])}`).join(' ')
        mismatches.push(`${spec.table} ${where} ${column}: sqlite ${a} != postgres ${b}`)
      }
    }
  }
  if (from.length !== to.length) {
    mismatches.push(
      `${spec.table}: ${from.length} rows in the source and ${to.length} in the target`,
    )
  }

  return {
    table: spec.table,
    sourceRows: from.length,
    targetRows: to.length,
    cells: rows * columns.length,
    mismatches,
    sourceDigest: digest(from, columns),
    targetDigest: digest(to, columns),
    columns: columns.map((c) => ({ source: profile(from, c), target: profile(to, c) })),
  }
}

/**
 * Read the whole shelf order out of both databases and compare it position by
 * position, then prove the comparison could have failed.
 *
 * The negative control is the part that matters. A `C` locale database orders
 * every column byte for byte whatever the column was declared as, so on one of
 * those the two lists agree for a reason that has nothing to do with
 * `COLLATE "C"` and the check is decoration. So: assert what collation the
 * database actually has, read the declarations back out of the catalogue rather
 * than trusting the DDL, and order the same rows under the database's own
 * collation to show that it produces a different answer.
 */
async function compareOrdering(source: Db, target: Db): Promise<OrderingCheck> {
  const ordered = 'SELECT id FROM books ORDER BY sort_key, id'
  const sourceOrder = (await source.all<{ id: number }>(ordered)).map((r) => Number(r.id))
  const targetOrder = (await target.all<{ id: number }>(ordered)).map((r) => Number(r.id))

  const disagreements: number[] = []
  for (let i = 0; i < Math.max(sourceOrder.length, targetOrder.length); i += 1) {
    if (sourceOrder[i] !== targetOrder[i]) disagreements.push(i)
  }

  const duplicates = await source.all<{ sort_key: string; n: number }>(
    `SELECT sort_key, CAST(COUNT(*) AS INTEGER) AS n FROM books
      GROUP BY sort_key HAVING COUNT(*) > 1 ORDER BY sort_key`,
  )

  const database = await target.get<{ collation: string }>(
    'SELECT datcollate AS collation FROM pg_database WHERE datname = current_database()',
  )
  const collation = database?.collation ?? '(unknown)'
  const linguistic = !/^(C|POSIX|C\.|ucs_basic)/i.test(collation)

  // The same rows, ordered by the database's collation instead of the column's.
  // Nothing is written and no column is changed: the clause applies to this
  // statement only.
  //
  // `COLLATE "default"` rather than the locale's own name, because "default"
  // always exists and names whatever this database was created with, while
  // `COLLATE "en_US.utf8"` is a collation object that a server is only entitled
  // to have if that locale was available when it was initialised.
  let controlDisagreements = 0
  let controlExample: string | null = null
  if (linguistic) {
    const control = await target.all<{ id: number; sort_key: string }>(
      'SELECT id, sort_key FROM books ORDER BY sort_key COLLATE "default", id',
    )
    const byteOrder = await target.all<{ id: number; sort_key: string }>(
      'SELECT id, sort_key FROM books ORDER BY sort_key, id',
    )
    for (let i = 0; i < control.length; i += 1) {
      const linguistically = control[i]
      const byBytes = byteOrder[i]
      if (!linguistically || !byBytes) break
      if (Number(linguistically.id) !== Number(byBytes.id)) {
        controlDisagreements += 1
        if (!controlExample) {
          controlExample =
            `position ${i}: byte order has ${byBytes.id} ` +
            `(${readable(byBytes.sort_key)}), ` +
            `${collation} has ${linguistically.id} (${readable(linguistically.sort_key)})`
        }
      }
    }
  }

  const declared = await target.all<{ table: string; column: string; collation: string }>(
    `SELECT c.relname AS "table", a.attname AS "column",
            COALESCE(l.collname, '(database default)') AS collation
       FROM pg_attribute a
       JOIN pg_class c ON c.oid = a.attrelid
       LEFT JOIN pg_collation l ON l.oid = a.attcollation
      WHERE a.attnum > 0 AND NOT a.attisdropped
        AND c.relname IN ('books', 'separators')`,
  )
  const declaredCollations = COLLATED_COLUMNS.map(([table, column]) => ({
    table,
    column,
    collation: declared.find((d) => d.table === table && d.column === column)?.collation
      ?? '(not found)',
  }))

  // Where each shelf begins, resolved the way shelves.ts resolves it. An
  // ordering difference too small to change the list but large enough to move
  // one book past a divider would show up here and nowhere else.
  const separators = await source.all<{ id: number; shelf_range: string; starts_at: string }>(
    'SELECT id, shelf_range, starts_at FROM separators ORDER BY shelf_range, position, id',
  )
  const firstAtOrAfter = async (db: Db, range: string, startsAt: string) => {
    const row = await db.get<{ id: number }>(
      `SELECT id FROM books WHERE shelf_range = ? AND sort_key >= ?
        ORDER BY sort_key, id LIMIT 1`,
      [range, startsAt],
    )
    return row ? Number(row.id) : null
  }
  const boundaries = []
  let boundaryDisagreements = 0
  for (const separator of separators) {
    const a = await firstAtOrAfter(source, separator.shelf_range, separator.starts_at)
    const b = await firstAtOrAfter(target, separator.shelf_range, separator.starts_at)
    if (a !== b) boundaryDisagreements += 1
    boundaries.push({
      separator: Number(separator.id),
      range: separator.shelf_range,
      sourceFirstBook: a,
      targetFirstBook: b,
    })
  }

  return {
    sourceOrder,
    targetOrder,
    disagreements,
    duplicateKeys: duplicates.map((d) => `${readable(d.sort_key)} (${d.n} books)`),
    databaseCollation: collation,
    collationIsLinguistic: linguistic,
    controlDisagreements,
    controlExample,
    declaredCollations,
    boundaries,
    boundaryDisagreements,
  }
}

/** A sort key with its unit separators shown, so a report is readable. */
export function readable(key: string): string {
  return key.replace(/\x1f/g, '|')
}

/**
 * Every cover filename the migrated rows point at, checked against the
 * directory the server would join them to.
 */
async function checkCovers(target: Db, directory: string): Promise<CoverCheck> {
  const names = new Set<string>()
  for (const [table, columns] of Object.entries(IMAGE_COLUMNS)) {
    const rows = await target.all<Row>(`SELECT ${quoted(columns)} FROM "${table}"`)
    for (const row of rows) {
      for (const column of columns) {
        const value = row[column]
        if (typeof value === 'string' && value !== '') names.add(value)
      }
    }
  }
  const missing: string[] = []
  for (const name of names) {
    if (!existsSync(join(directory, name))) missing.push(name)
  }
  return { directory, referenced: names.size, present: names.size - missing.length, missing }
}

async function checkSequences(target: Db): Promise<SequenceCheck[]> {
  const checks: SequenceCheck[] = []
  for (const { table, identity } of TABLES) {
    if (!identity) continue
    const max = await target.get<{ max: number | null }>(`SELECT MAX(id) AS max FROM "${table}"`)
    const sequence = await target.get<{ name: string | null }>(
      `SELECT pg_get_serial_sequence(?, 'id') AS name`, [table],
    )
    let next = 0
    if (sequence?.name) {
      // last_value and is_called rather than nextval, which would consume one.
      const state = await target.get<{ last_value: string; is_called: boolean }>(
        `SELECT last_value, is_called FROM ${sequence.name}`,
      )
      if (state) next = Number(state.last_value) + (state.is_called ? 1 : 0)
    }
    const maxId = max?.max === null || max?.max === undefined ? null : Number(max.max)
    checks.push({ table, maxId, nextId: next, ok: next > (maxId ?? 0) })
  }
  return checks
}

/**
 * Re-read both databases and prove the migration did nothing to the catalogue.
 *
 * Deliberately re-reads rather than checking what `migrateCatalogue` believed it
 * wrote. A writer that miscounted would report its own miscount as agreement.
 */
export async function verifyCatalogue(
  source: Db,
  target: Db,
  options: { coverDir?: string; onNote?: Note } = {},
): Promise<VerifyReport> {
  const note = options.onNote ?? (() => {})
  const started = Date.now()
  const problems: string[] = []

  const tables: TableComparison[] = []
  for (const spec of TABLES) {
    const comparison = await compareTable(source, target, spec)
    tables.push(comparison)
    if (comparison.sourceRows !== comparison.targetRows) {
      problems.push(
        `${spec.table}: ${comparison.sourceRows} rows in, ${comparison.targetRows} out`,
      )
    }
    if (comparison.sourceDigest !== comparison.targetDigest) {
      problems.push(`${spec.table}: content digests differ`)
    }
    problems.push(...comparison.mismatches)
    note(
      `${spec.table.padEnd(14)} ${String(comparison.sourceRows).padStart(6)} -> ` +
      `${String(comparison.targetRows).padStart(6)}  ` +
      `${comparison.sourceDigest === comparison.targetDigest ? 'identical' : 'DIFFERENT'}`,
    )
  }

  const ordering = await compareOrdering(source, target)
  if (ordering.disagreements.length) {
    problems.push(
      `the shelf order differs at ${ordering.disagreements.length} of ` +
      `${ordering.sourceOrder.length} positions, first at ` +
      `${ordering.disagreements[0]}`,
    )
  }
  for (const declared of ordering.declaredCollations) {
    if (declared.collation !== 'C') {
      problems.push(
        `${declared.table}.${declared.column} is collated ${declared.collation}, not C`,
      )
    }
  }
  if (!ordering.collationIsLinguistic) {
    problems.push(
      `the target database's collation is ${ordering.databaseCollation}, which is byte ` +
      `order, so the ordering comparison would pass whatever the columns said. ` +
      `Rehearse against a database created with a linguistic collation.`,
    )
  } else if (ordering.controlDisagreements === 0) {
    problems.push(
      `the negative control found no difference: this catalogue's sort keys order ` +
      `the same way under ${ordering.databaseCollation} as under byte order, so the ` +
      `ordering comparison above did not discriminate.`,
    )
  }
  if (ordering.boundaryDisagreements) {
    problems.push(
      `${ordering.boundaryDisagreements} shelf boundaries resolve to a different book`,
    )
  }

  const covers = options.coverDir ? await checkCovers(target, options.coverDir) : null
  if (covers?.missing.length) {
    problems.push(
      `${covers.missing.length} of ${covers.referenced} cover files are not in ` +
      `${covers.directory}`,
    )
  }

  const sequences = await checkSequences(target)
  for (const sequence of sequences) {
    if (!sequence.ok) {
      problems.push(
        `${sequence.table}: the next id is ${sequence.nextId} and the highest in the ` +
        `table is ${sequence.maxId}, so the next insert collides`,
      )
    }
  }

  return { tables, ordering, covers, sequences, problems, elapsedMs: Date.now() - started }
}
